### ISSUE TITLE
Automatische initiele sortProperties volgord met heuristics uit scriptie van Falco Paul

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#14]
Ik begeleid OU Masters afstudeerder Falco Paul. Hij verdedigt zijn scriptie op 9 december 2014. Hij onderzoekt de "beste" automatisch volgorde van Semantic Web properties op browser interfaces. Hij heeft bepaalde dat een heuristic algorithm beter doet dan random, alphabetisch en enkele tekstgebaseerde technieken. Dus laten wij zijn beste (tot nu toe) heuristieken gebruiken. Ook aardig om onderzoekscontext toe te passen in deze implementatie.

De laatste versie van zijn scriptiedocument is op de ABI30 wiki op http://is.cs.ou.nl/ABI30/index.php5/File:Thesis_Falco_Paul.pdf en gelinkt van de homepagina. Zijn heuristic techniek wordt beschreven in "7.5 Experiment: heuristics based ranking"  op pagina 73.

**Comment by TeunTheunissen** [comment]
In revisie 485 en 486 is de alfabetische sortering geimplementeerd.De schaalbaarheid is weer iets verbeterd omdat de propertylabels array niet meer gesorteerd wordt bij het opvragen ervan door de draw methode van de lensbox.
Dit is de eerste stap op weg naar de heuristische sorteer methode. Deze standaard sorteer methode is ter vergelijking met de heuristische versie.
@AlexMekkering graag reviewen.

**Comment by AlexMekkering** [comment]
@TeunTheunissen Volgens mij is er iets misgegaan bij je commits. r486 is namelijk een volledige revert van r485.

**Comment by TeunTheunissen** [comment]
Alex dat klopt ik had de switch van de trunc naar de branch laten staan bij de commit.
Ik heb de branch gereverd en weer gecommit naar rev 488. Deze revisie is gemerged met de laatste revisie van de trunc. Het zou nu goed moeten zijn.
@AlexMekkering  graag weer reviewen.

**Comment by TeunTheunissen** [comment]
@AlexMekkering ik heb de wijzigingen gecommit naar revisie 504 in de branch 'teun\SortProperties'.
Zou jij daar een blik op willen werpen?

**Comment by TeunTheunissen** [comment]
Wijzigingen op de branch SortProperties gecommit naar revisie 518.
Unittests zijn toegevoegd.
@AlexMekkering zou jij willen reviewen?
Ik heb de branch nog niet gemerged met de trunc. Dat wou ik doen als jij ernaar gekeken hebt.

**Comment by AlexMekkering** [comment]
Ziet er goed uit, ik ben onder de indruk van wat je in die relatief korte tijd voor elkaar hebt gekregen :+1:. Het lijkt zo op het eerste oog helemaal te voldoen aan het algoritme wat Falco Paul beschreven heeft in zijn paper.
Onderwijl heb je in r504 zelfs nog één van de features uit de feature tabel geïmplementeerd, namelijk het verwerken van rdfs:label annotaties van de bronontologie naar initiele labels in FresnelForms, dus wederom petje af :clap:! (Wil je deze ook nog even bijwerken in de feature table? #43)
Ook het statistics venster in de GUI is een leuke en, uit onderzoeksperspectief gezien, nuttige aanvulling.

Ik heb daarom op zich niet zoveel commentaar, maar heb toch nog wat kleine dingen kunnen vinden:
 - In de PropertyLabelHeuristicComparator komt bij Bucket E de property foaf:givenname 2x voor. Aangezien je toch case-insesitive matcht, kun je er dan net zo goed één weglaten.
 - In de PropertyLabelHeuristicComparator.getbucket heb je een flink aantal if-statements genest (telkens in else takken). Je kunt hier ook `} else if (...) {` voor gebruiken, dat scheelt een hoop nesting en ziet er iets schoner uit.
 - Je hebt een GUI optie toegevoegd om naar alfabetische volgorde over te stappen. Er is echter geen weg terug naar heuristics anders dan weer een default fresnel uit te voeren.
 - Ik zie in svn geen specifieke unittests staan die van belang zijn voor deze sortering, dus ik denk dat je het bijbehorende bestand vergeten bent toe te voegen aan svn (TortoiseSVN->Add).

**Comment by TeunTheunissen** [comment]
Dank voor het commentaar. De feature tabel in het excel sheet is bijgewerkt.
De duplicaat van foaf:givenname is verwijdert.
De 'else if' heb ik toegepast en dat ziet er veel beter uit, dank.
De default volgorde is die zoals fresnel generator de properties uit de ontology leest, dus niet de heuristic sortering. Je kan zowel de alfabetische als de heuristic sortering activeren op een lens maar er is geen optie om terug te gaan naar de oorspronkelijke propertie volgorde. Alleen door de  default fresnel weer uit te voeren.
De unit test is toegevoegd aan de branch.

**Comment by TeunTheunissen** [comment]
De trunc is gemerged met de sortproperties branch.
De build gaat prima. @AlexMekkering , @jheijning  Zouden jullie nog even willen testen of alles naar behoren werkt?
zoja dan kan dit issue gesloten worden

**Comment by AlexMekkering** [comment]
Ik heb de merge revisie terug gedraaid omdat alle wijzigingen die tussentijds op de trunk gedaan waren, ermee waren gerevert. @TeunTheunissen, wil je even kijken of je de merge kunt uitvoeren zonder alle tussentijdse wijzigingen op trunk terug te draaien?

**Comment by TeunTheunissen** [comment]
Heren, ik weer een poging gewaagd. de trunc is gemerged met de branch sortproperties.
Vanwege het "wees properties" issue heeft de classe actor de birthday property niet meer.   
Ik heb een aangepaste 'JamesDean' ontology  'JeamesDeanMovies_heuristicsorttest.owl' aan de tests toegevoegd zodat de build succesvol verloopt.
Het probleem was dat properties die als domein persoon hadden nu niet meer golden voor de subclasse Actor. Ik heb de properties nu als domein de Actor klasse gegeven waardoor de testen voor de heuristic sortering weer succesvol verlopen.

Zover ik kan overzien zou het gelukt moeten zijn, graag jullie commentaar.

Vr. gr. Teun

**Comment by AlexMekkering** [comment]
Reviewcomment has been integrated and the svn merge was executed correctly, so this one can be closed.
