### ISSUE TITLE
URLs voor classes en properties op Fresnel GUI duidelijk

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#15]
Op de GUI zie een een label per lens en per property per lens. Maar het is niet altijd specifiek genoeg welke URI erbij hoort. Dus graag een duidelijke URI per property op elke lens en voor de class dat elke lens vertegenwoordigt. Dus (eerste stap minstens) vervang huidige labels op GUI met de URI.

URI kan met namespace prefix en dan ID. Liefts consequent met de huidige Protégé sessie, met de opties ervoor, maar die is een onderdeel issue die minder belangrijk is. In ieder geval misnstens prefix:ID. Eventueel zonder prefix voor default namespace.

Fresnel heeft labels voor lensen en properties. Die horen ook in de GUI te komen. Maar die is een andere issue.

De Getty onto op http://vocab.getty.edu/ontology.rdf is een goed test onto. Ook omdat het meerdere imported ontologies heeft met herhaalde ID's tussen namespaces.

**Comment by AlexMekkering** [comment]
Op dit moment hebben de lenzen op het scherm een label welke de naam van de lens zelf is. Een lens voor bijvoorbeeld klasse skos:Concept heeft het label 'ConceptLens' op het scherm.
Is het de bedoeling dat de labels precies gelijk worden aan de naam van de klasse waar het voor dient (dus zonder Lens achtervoegsel)?

Mijn mening is dat het, nu we de plugin geschikt hebben gemaakt voor het leveren van kant-en-klare presentatie (op dit moment in de vorm van Semantic MediaWiki syntaxis), wellicht de tijd is om de GUI elementen wat meer abstract te gaan bekijken en niet per se in termen van Fresnel. De presentatie van ontologie-elementen kan dan intern nog (zoveel mogelijk) als fresnel lenzen, formats en groups worden behandeld, maar wat de gebruiker getoond wordt kan een meer abstracte vorm hebben. In dit verhaal past een weergave van lenzen als 'selecties van eigenschappen van klassen', waarin het label inderdaad geen 'Lens' achtervoegsel heeft. De specifieke vorm van de presentatie van de verschillende elementen van een ontologie (het uiterlijk van property namen, waarden, labels, etc.) kan dan intern behandeld worden als fresnel format, in de GUI zal dit dan ook een meer abstracte vorm dienen te krijgen (niet meer in fresnel termen).

Zie ook #30 voor een abstractere benadering van lenzen.

**Comment by AlexMekkering** [comment]
Geïmplementeerd in r251.

De aanpassing was alles behalve triviaal en heeft letterlijk elk package getroffen. Review hiervan zal derhalve niet eenvoudig zijn, dus ik stel voor dat @jheijning en @TeunTheunissen beiden in ieder geval functioneel even checken of het doet wat er van de plugin verwacht wordt en bij voorkeur toch de code globaal proberen te beoordelen. (Tip: de Getty onto zoals Lloyd had aangegeven is leuk om te bekijken :smile:). 

Globaal gezien zijn in de gehele plugin de 'gewone' namen verdwenen, dus die zonder namespace. Voor elk element wat gebaseerd is op een URI wordt er nu ook alleen gebruik gemaakt van die URI. 
Deze URI wordt vervolgens gebruikt om de naam van het element te bepalen wanneer dat getoond moet worden (wordt alleen gebruikt voor de GUI, intern worden dus slechts URI's gebruikt).
Wanneer een prefix bepaald kan worden bij het betreffende element, wordt de geprefixte variant ervan gebruikt als naam. Wanneer geen prefix  bepaald kan worden, wordt de volledige URI als naam gebruikt.

Er blijven wat mij betreft nog een paar issues over, misschien kan @LloydRutledge hier helderheid over geven:
- Er kunnen properties worden toegevoegd aan een lens. In dat scherm kan ook een naam worden ingevoegd, maar die wordt op dit moment nergens gebruikt aangezien de namen dynamisch op basis van de URIs bepaald worden (labels kunnen nog wel steeds gewijzigd worden natuurlijk). Kunnen we die naam gewoon weghalen?
- De Fresnel formats in het outputbestand voor formatted properties (apart label, custom style, etc.) worden nog steeds als volgt genoemd ":<property><lens>Format". Hierbij is <property> de lokale naam van de property, dus zonder namespace en voor <lens> geldt hetzelfde. Om ook dit uniek te maken zouden hiervoor ook de prefixes als extra moeten worden gebruikt, maar dan wordt het waarschijnlijk wel een stuk langer. Wat vindt jij?
- Eigenlijk geldt hetzelfde ook voor de gegenereerde Fresnel Lenzen (in het output bestand) in het algemeen: Een :<naam>Lens zou om pertinent uniek te zijn, de prefix in de naam moeten gebruiken, dus :<prefix><naam>Lens. De vraag is of dit in de praktijk wel nodig is; de meeste lenzen zijn volgens mij wel uniek in naamgeving (dus ook zonder namespace).

**Comment by LloydRutledge** [comment]
Bedankt, Alex!

Ja, property naam invoegenkan weg. Dan heb je of de URI met (meestal) namespace en ID als default label en die toont.

De format en lens URI ID's mag wel lang zijn als dat uniciteit gegarandeerd. En dat is niet erg als alleen de machine en niet de mens het ziets - dus als het in de RDF komt maar niet of nauwelijks in de interfae van Protégé.

**Comment by AlexMekkering** [comment]
Ik heb zojuist in 2 afzonderlijke commits (r253 & r254) zowel de naam op het "create property" dialoog verwijderd als de namen van lenzen/formaten in het output-bestand per definitie uniek gemaakt.
Bij het verwijderen van het naamveld op de "create property" dialoog heb ik de vrijheid genomen om ook het index veld te verwijderen en een nieuw toegevoegde property automatisch onderaan de lijst te plaatsen. Ik vond die index alleen maar verwarrend en aangezien je een property toch eenvoudig kunt verplaatsen door te slepen vond ik het ook niet echt iets toevoegen, ik hoop dat jullie het hiermee eens zijn.

Voor het uniek maken van de output geldt dat alle namen bepaald worden door:
- de prefixed versie van een uri te nemen,
- vervolgens de : te vervangen door een - om het een geldig fragment te laten zijn.
- voordat de : vervangen wordt, worden alle reeds aanwezige - vervangen door --, waardoor er altijd een unieke naam ontstaat.
- namen die niet te prefixen zijn worden zogenaamd uri-encoded weggeschreven om het een geldig fragment te laten zijn.

Het effect van deze actie is dat wat voorheen :ThingLens heette, nu :owl-ThingLens is geworden. Alle lenzen en formaten van klassen of properties binnen de default namespace van de ontology, hebben echter dezelfde naam kunnen behouden waardoor ook de output nog enigszins human readable is gebleven :smiley: 

Dus... alle issues voor dit onderdeel zijn wat mij betreft opgelost.

**Comment by jheijning** [comment]
Dat was een behoorlijke lap aangepaste code :-)
Ik heb heel globaal gescand en de plugin functioneel gechecked, inclusief een wiki-import.

Het werkt allemaal zoals verwacht, goed werk! Een heel klein dingetje uit de save to wiki .xml file: 
![captura](https://cloud.githubusercontent.com/assets/9306134/5751340/5b5c8cea-9c62-11e4-8e26-c825f6fe7598.PNG)

Property:Est moet Property:Test zijn, zie "equivalent URI" in dezelfde foto. Dus waarschijnlijk een substring index verkeerd.

**Comment by AlexMekkering** [comment]
Ik denk dat het het probleem van het voorbeeld hierboven zit in het feit dat hier waarschijnlijk een test-URI "test" is gebruikt welk niet voldoet aan de URI syntax (zie https://tools.ietf.org/html/rfc3986#section-3). De scheme én path van een URI zijn verplicht en worden gescheiden door een :. Hierdoor bepaalt Jena dan waarschijnlijk dat de localname van de URI gelijk is aan "est" (waarschijnlijk omdat er geen : in de URI aanwezig is terwijl daar wel vanuit gegaan wordt.

**Comment by jheijning** [comment]
ah ok, ja klopt, ik had om te testen een property "test" in de plugin toegevoegd aan een lens.

**Comment by TeunTheunissen** [comment]
Ik heb eerst maar even een functionel test gedaan en het ziet er goed uit.
2 kleine puntjes, die staan hieronder:

Als test de shakespeare.owl ontologie gebruikt.

een propertie toegevoegd aan de fresnel definitie met de gui:
Lens/classe 'lit:Person' daaraan heb ik toegevoegd de propertie 'surname'.

Bij het bewaren van de fresnel heb ik geen extensie opgegeven en het bestand wordt dan ook bewaard zonder extensie. Het zou de extensie n3 moeten krijgen.

Het laden van de bewaarde fresnel geeft voor de toegevoegde propertie
'surname' de gehele (default) url als prefix. in plaats van de 'surname' of ':surname'.
Vr.gr. Teun

**Comment by AlexMekkering** [comment]
Bij het opgeven van een property werd voorheen en wordt nog steeds gevraagd om een URI, hieraan is voor dit issue niets gewijzigd. 'surname' is geen geldige uri (moet minstens uit een scheme en een path bestaan, gescheiden door een : (nogmaals, zie https://tools.ietf.org/html/rfc3986#section-3). Ik denk dat Jena er toch iets van probeert te maken door er de default namespace maar voor te plaatsen, maar dat valt denk ik buiten de strekking van dit issue.
Wellicht is er een methode om te checken of iets een geldige URI is zodat we dat in de toekomst kunnen gaan gebruiken. Ik kan morgen nog even kijken of er iets voor is, maar anders wil ik voorstellen om hier een 'enhancement' issue voor te maken zodat het huidige issue kan worden afgesloten en we uit kunnen zoeken wat ervoor nodig is.

Wat betreft de default extensie: Dat is geen onderdeel van dit issue, maar had een bevinding kunnen zijn van issue #33 die je net gesloten hebt :wink:. 't Is namelijk aangepast voor #33 in r234.

**Comment by jheijning** [comment]
#33  zie commentaar.

**Comment by TeunTheunissen** [comment]
Daar ben ik het mee eens deze afsluiten en een nieuw issue maken om dit uit te zoeken.
