### ISSUE TITLE
Default Frensnel of Load knop klikken met actieve Fresnel graph

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#22]
Wat gaat en moet gebeuren als de gebruiker op de "Default Fresnel" of "Load Fresnel" knop klikt als een graph al actief is met Fresnel die en/of:
- van default is
- is ge-edit
- is ingelezen van een Fresnel bestand.

ik stel voor als korte termijn oplossing dat de huidige graph gewoon verdwijnt een vervangen wordt door de gegeneerde default of opgelade bestand. De gebruiker moet dan voorzichtig met die knoppen zijn, maar deze is een onderzoeks project, geen commerciele product.

Is deze al het gedrag? Zo ja, case closed (voorlopig). Zo niet, wat gebeurt er dan wel? Is het makkelijk om gewoon de al actief Fresnel te wissen en door de nieuwe Fresnel te vervangen?

Hebben jullie voorstellen voor het ideël, langere termijn oplossing? De knoppen uitgrijzen als de graph niet leeg is bvb? Misschien is dat de makkelijkste te implementeren. Die is ook de helderste voor de gebruiker, hoevel het ook als beperkt ervaren kan worden.

**Comment by TeunTheunissen** [comment]
issue #22 is solved in revision 225, Joop, A happy newyear  to you, would you be so kind to review this one, Alex is reviewing already another issue of mine.
Teun

**Comment by jheijning** [comment]
Review: Lijkt mij een mooie oplossing!
code: ik heb de "break" refactored naar een meer standaardvorm.
