### ISSUE TITLE
DBpedia ontologie draait goed in tool

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#26]
De DBpedia ontologie is een belangrijk ontologie voor de Forms paper vanwege zijn relatie met Wikipedia en haar infoboxes die als doel een voorbeeld in de paper genoemd gaan worden, zoals die al gebruikt zijn in de 2013 paper. Een breed doel voor deze tool en aanpak is dat zie op infoboxes in Wikipedia toegepast zouden kunnen worden. Met focus op de sleutelvoorbeeld van Person als infobox en Tim Berners-Lee als pagina die de infobox gebruikt. Dus als je de DBpedia ontologie in je Protégé sessie zet, hoe kan je de Person infobox met Fresnel Forms aanpassen om de Wikipedia infobox te na-apen?

Deze is dus een soort brede, abstract user story: zou je de Wikipedia infoboxes met Fresnel Forms kunnen maken en onderhouden? Met de volgende eisen:

- automatische gegeneerde default/initiele lensen zijn goed beginpunten voor doel
- GUI kan makkeljik de infobox lensen fine-tunen om preciesere op de bron-infoboxes te lijken
- De genereerde wiki-formulieren werken goed voor het invullen van infobox instanties
- kan tegen omvang: minder belangrijk dan dat het goed werkt voor enkele infoboxes

Erbij komt een omvang vraag: DBpedia is enorm, met veel infoboxes. Dus interessant te zien hoe Fresnel Forms er tegen kan.

Stappen:
- DBpedia ontologie vinden als oplaadbare URL of bestand
- In Fresnel Forms proberen
- Bekijken welke omvang kwesties verschijnen
- Person infobox testen: zo nodig met uittrekseltje van DBpedia ontologie

**Comment by jheijning** [comment]
Één ding om mee rekening te houden is dat special:import dat we nu gebruiken een limiet van +- 100 pages heeft. http://www.mediawiki.org/wiki/Manual:Importing_XML_dumps#Using_Special:Import . Een manier om hiermee om te gaan zou kunnen zijn om in batches van 100 pagina's te exporteren, dat is een simpele aanpassing.

**Comment by LloydRutledge** [comment]
Goed gezien, Joop. Dat limietprobleem is niet van ons maar van de gebruiker. Dus laten we geen zorg meer over makken tenzij we heel makkelijk een oplossing kunnen bieden.

En er zijn oplossingen voor de gebruiker. Je gelaagde batch oplossing is een. Men kan ook die limiet ook aanpassing op de eigen LocalSettings.php. Plus volgens mij is er een /maintenance/ .php die de XML install doet zonder limiet. Daarvoor moet je operating system toegang hebben, en misschien ook een superuser erop zijn. Maar dat kunnen we vragen van een wikimaster volgens mij, en voor hem/haar is deze PHP command line install heel makkelijk.

**Comment by LloydRutledge** [comment]
@TeunTheunissen, kan je https://svnext.ou.nl/INF_Studenten_ABI_team30/Environment%20&%20Misc/Ontologies/DBPedia_TBL_Extract/dbpedia_2014_TBL_extract.owl aanpassen zodat de URI niet van dbpedia is maar van ons? Het is beleefd dat als men een nieuwe URI verzint dat ie een eigen domain gebruikt.

**Comment by TeunTheunissen** [comment]
@LloydRutledge Ik heb de TBL extraction ontology hernoemt naar 'owf_style_TBL_extract.owl'. Verder heb Ik de namespace van de ontology aangepast naar :
http://is.cs.ou.nl/OWF/owf_style_tim_berners_lee_extract
Is dit wat je bedoelde?

**Comment by LloydRutledge** [comment]
Is goed, bedankt.

**Comment by TeunTheunissen** [comment]
De userinterface is aangepast zodat lensen uit dbpedia geexporteerd kunnen worden.
Voor de beschrijving en de instructie  zie het document 'Userinterface instructie.docx' in de map 'design'.
Zie bijgaande screenshot voor een idee:

![ff_userinterface](https://cloud.githubusercontent.com/assets/9306315/6488051/22cdd8a8-c295-11e4-8f34-91a605314889.jpg)

@AlexMekkering Graag de userinterface testen en code reviewen.

**Comment by AlexMekkering** [comment]
Slimme oplossing! Het geheel werkt nu redelijk vloeiend met de complete DBPedia onto :+1:

Vwb een oppervlakkige review:
 - Zo hier en daar is de formattering van de code nog niet automatisch bijgewerkt (Ctrl+Shift+F)
 - Er zijn nog wat checkstyle meldingen welke eenvoudig kunnen worden opgelost
 - Voor LensDiagram.hideall klopt de javadoc niet helemaal

Vwb de eerste testen (reeds deels gecommuniceerd via mail):
 - 

 > Waar ik, intuïtief gezien zonder de UI instrucie te hebben gelezen, tegenaan liep is het feit dat de lenzen rood worden wanneer je erop klikt, maar wanneer je meerdere lenzen geselecteerd hebt op die manier, de acties slechts van toepassing zijn op de lens waar je op dat moment op geklikt hebt. Dus wat ik me eigenlijk afvraag is: Wat heeft het selecteren van lenzen voor zin, wanneer de acties achter de rechtermuisknop alleen van toepassing zijn op de lens waarop geklikt is.

- Voor een aantal lenzen geldt dat ze, wanneer ze uitgeklapt worden, in de hoogte niet passen.
- Ook de breedte lijkt niet helemaal te passen (rechts vallen er volgens mij wat lijntjes weg).
- Wanneer lenzen uitgeklapt worden vallen ze óf over andere lenzen heen óf er juist onderdoor. Wanneer je een lens dan iets wilt verplaatsen, zoekt die echter een eigen lege plek onder, of boven andere lenzen op.

**Comment by AlexMekkering** [comment]
M.b.t. schaalbaarheid heb ik in r435 het verwerken van property labels iets gerefactored: het eventueel inkorten van labels wordt nu iets slimmer gedaan. @TeunTheunissen, please review.

**Comment by TeunTheunissen** [comment]
In Revisie 437 de checkstyle codes opgeheven en de javadoc is aangepast.
Het rechtermuis menu voor een lensbox kan voorzien worden van menuitems voor de geselecteerde items omdat de afzonderlijke lensboxen ook ingesteld moeten kunnen worden. (ook als ze geselecteerd zijn) De functie van het selecteren was om de lensbox te kunnen bekijken/onderscheiden t.o.v het geheel, niet om functies op meerdere lensboxen los te laten.
Het klopt dat als lensen uitgeklapt worden ze niet kunnen passen in het schema, daarvoor is het canvas rechtermuis item 'rearrange', die past het gehele schema aan.
De breedte ga ik naar kijken
Het punt dat opengeklapte lensen die onder een andere lens worden getekend zal ik gaan bekijken.
De review van revisie r435 is OK, de lensbox laat mooi de suffix zien bij lange attribuut namen.

**Comment by TeunTheunissen** [comment]
In revies 438 is het probleem van de overlappende lensboxen verholpen door de lensboxen die hoger in de hierarchie staan te laten overlappen t.o.v de lensboxen die lager in de hierarchie staan.
Hiervoor wordt de zorder geinitialiseerd als de negatie van het level zorder = -1*level in de initLayer methode.
@AlexMekkering  please review.

**Comment by TeunTheunissen** [comment]
Mousemove concurrency error opgelostin revisie 444. Niet door een synchronised blok maar door de sortering naar de resetLensposition te verplaatsen. Dit zou het tekenen ook weer een beetje moeten versnellen. 
@jheijning  graag reviewen door te testen of de fout nog optreed bij een mousemove. Daarna maak ik de nieuwe revisie aan voor Lloyd.

**Comment by jheijning** [comment]
Fout treedt niet meer op.

**Comment by AlexMekkering** [comment]
Review ook OK, dus terecht gesloten.
