### ISSUE TITLE
XML import inpakking

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#28]
Je kan de XML import code gemakkelijke generen via enkele sjablonen voor de XML verpakking. Elke wiki XML import-bestand kan beginnen met deze text:

<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.5/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.5/ http://www.mediawiki.org/xml/export-0.5.xsd" version="0.5" xml:lang="en">

en eindigen met:

</mediawiki>

En tussen in heb je de pagina's voor de infoboxes, hun forms, de properties en de category pagina's voor de classes. Per pagina heb je een stuk XML code. Die kan je beginnen met:

<page>
 <title>PAGENAME</title>
 <revision>
  <timestamp>2008-03-071T16:58:00Z</timestamp>
  <contributor>
   <username>Fresnel Forms generation</username>
   <id>1</id>
  </contributor>
  <comment>generated by Fresnel Forms on Protégé</comment>
 <text xml:space="preserve">

Hier, natuurlijk, is "PAGENAME" de naam dat je wilt voor de pagina. De timestamp is nodig en zijn waard maakt niet uit, als het maar in het geleden is. Het meest netjes is natuurlijk de huidige tijd.

En de verpakking per pagina eindigt natuurlijk met:

</text></revision></page>

Tussenin zet je gewoon de wikipagina-code dat je op die wikipagina wilt. Voor een form op de "Form:" pagina-namespace wordt dit Semantic Forms code.

Joop, ik hoop dat je hiermee goed kan beginnen.

**Comment by AlexMekkering** [comment]
Wat mij betreft is deze opgelost met #7, waarbij deze techniek gebruikt is om de gegenereerde pagina's te kunnen importeren in SMW.
