### ISSUE TITLE
Fresnel plus OWF extension ontologie moet alle informatie nodig hebben voor fresnel2wiki

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#29]
We werken met een ontologie die Fresnel uitbreidt, met zoveel gebruik van Fresnel mogelijk waar het van toepassing is. Waar we iets nodig hebben die niet in Fresnel is dan moet we dat toevoegen in ons eigen ontologie die Fresnel importeert en uitbreidt. Deze ontologie moet alle informatie houden dat de  zijn conversie naar wiki-code nodig heeft. De PHP OWF queryt zowel Fresnel als de bron ontologie.

De bron ontologie is ervoor nodig voor bijvoorgeeld de rdfs:ranges om de autocompletion te bepalen. Daar heeft Fresnel niks voor. Dus moet dat informatie in ons uitbreiding komen.

Een motivatie hiervoor is dat de men ontwerper deze stijl zelf kan aanpassen

**Comment by LloydRutledge** [comment]
enige die nog moet is range

**Comment by jheijning** [comment]
We hadden het er al kort over in de vergadering: Sommige properties in de tim berners-lee infobox hebben meerdere values. De grootste uitdaging daarin lijkt mij niet zo zeer te zijn dat het aantal > 1, maar eerder dat bijvoorbeeld in de "born" property in de nieuwste infobox op http://en.wikipedia.org/wiki/Tim_Berners-Lee values van verschillende types heeft. Dus kan een property dan meerdere ranges hebben?

**Comment by jheijning** [comment]
Ik zet Alex er ook even bij, ook al heeft Alex er niet direct mee te maken.

**Comment by LloydRutledge** [comment]
Dat een property meerdere values heeft betekent in SW gewoon meerdere triples met dezelfde subject en predicate, maar dan verschillende objecten of data waarden.Op de Semantic Forms betent dit dat je een arraymap moet gebruiken. De Forms documentatie heeft er instructies voor. Of voorbeelden worden gegeneerde via de meta-formulieren voor het opstellen van Forms op Forms.Is zie "Born" als een Fresnel sublens die "born" heet, met erin property-rijen voor naam, datum en plaats. Born is dus geen property maar een groepering van properties. Misschien is het nuttig als Teun opstelt hoe dit deel van dit voorbeeld in Fresnel opgesteld wordt.

**Comment by TeunTheunissen** [comment]
Ik ga ermee aan de slag.

**Comment by TeunTheunissen** [comment]
Ik heb een eerste versie gemaakt van de fresnel_owf.owl ontology.
In deze versie is een fresnel.range gedefinieerd en uitbreidingen van de fresnel.Purpose classe met individuals.
In de designmap het document 'Issue29_range in fresnel definieren.docx' toegevoegd.
Hierin wordt de fresnel.range beschreven en de fresnel.Purpose individuals.
Ook wordt een opzet gegeven van het birthFact probleem zoals Lloyd het heeft voorgesteld met sublensen.
Graag commentaar.
Groeten Teun

**Comment by LloydRutledge** [comment]
http://is.cs.ou.nl/OWF/# is goed base URI for de OWF namespace. Je hebt het over "owf:range" dus neem ik aan. Ik wil liever dat de namen consequent gebasseerd worden op de wiki componenten die die gaan gebruiken. Of nog liever de XForms equivalent.Hier denk ik dus aan "owf:autocompleteOnClass" als vertalling van de Semantic Forms field "autocomplete on category". En dan aardige als je consequent bent zowel qua benaming als qua structuur met hoe je de Semantic Forms syntaxis mapt aan je ontologie. En hetzelfde met syntaxis van elders in (Semantic) MediaWiki.

Waar is dit bestand "fresnel_owf.owl "?

**Comment by TeunTheunissen** [comment]
Mooi dat je het eens bent met de base URI, het bestand fresnel_owf.owl definieerd uitbreidingen op fresnel dus de range property wordt 'fresnel:range' en niet 'owf:range'. 
Het bestand fresnel_owf.owl staat in onze repository onder de map:
'Environment & Misc\Ontologies\OWF'
Ik zal de synatxis en de structuur van semantic forms volgen bij aanmaken van nieuwe uitbreidingen.

Is er een mogelijkheid om het owl bestand via de uri http://is.cs.ou.nl/owf beschikbaar te krijgen?

Vr. gr.
Teun

**Comment by LloydRutledge** [comment]
Ik regel accounts voor jullie zodat je de onto daar kan zetten. Het begin van dat bestand heeft "<file://D:/My%20Documents/protege/fresnel_owf>""-- werkt alleen op je computer natuurlijk Teun.
Gebruik van domain is goed uitbreiding van Fresnel. Range naar property en class is ook goed SW equivalent van wat er op de wiki gebeurt. Blijf dergelijk relaties goed erbij houden.

Kan je een versie nummer in de code zetten, met uitleg comment erbij over hoe het werking-in-uitvoering is?

Zoal boven geschreven wil ik enkele consequent toegepast practices. Zoals de namen en structuur uit de syntaxis van Semantic Forms en andere (S)MW componenten zo direct mogelijke toepassen. Of liever XForms waar die equivalenten van de wiki syntaxis heeft.

Het is een aardig begin. We kunnen de groei goed scrummen. Ik neem aan dat de groei component per component wordt. Dus als iets in de naar wiki vertaling komt dat die dan ook goed in de ontologie zit.

**Comment by TeunTheunissen** [comment]
Dank voor de accounts, Ik ben me ervan bewust dat deze ontology alleen op mijn pc werkt. Als we toegang hebben tot de server maak ik hem publiek toegankelijk.
Ik heb de termen aangepast naar Semantic Wiki Forms termen, het commentaar aangepast en het versie nummer aangepast. Laat maar weten wat je ervan vindt.
Vr.gr.Teun

**Comment by AlexMekkering** [comment]
Moeten we dan overal de prefix "fresnel:" laten verwijzen naar de door onszelf 'extended' variant?
En hoe gaan we om met bijv. owf:xpos en owf:ypos? Deze gegevens zijn voor ons belangrijk maar betreffen geen presentatiegegevens en horen wat mij betreft niet in de extended versie terecht maar in een aparte ontologie zoals nu?

**Comment by TeunTheunissen** [comment]
Onze extended variant, breid de fresnel ontology uit, alle termen die wij definieren hebben gewoon de prefix fresnel:. Dus de autocompletionOnClass wordt genoteerd als fresnel:autocomplletionOnClass.
Wat betreft de owf:xpos en ypos, die horen wat mij betreft helemaal niet thuis in de ontology, het zijn gegevens die horen bij de plugin en niet bij de definitie van de wiki forms. Heeft de protege api niet een mogelijkheid om die 'locale' gegevens ergens in op te slaan?. Zoiets als het oude vertrouwde ini bestand?
 Vr. gr.Teun

**Comment by LloydRutledge** [comment]
Eigenlijk is de fresnel namespace niet van ons en dus moeten we geen nieuwe URI's erin maken. Dus elke URI dat wij maken moeten we in de owf namespace zetten. En bij elke component moet het duidelijk zijn van welke ontologie die komt inclusief OWF. Dus maak a.u.b. namespace prefixes voor zowel fresnel als owf en gebruik allebei. En voor de duidelijkeheid de base namespace for owf. Deze practice zie je in onder andere. SKOS op http://www.w3.org/2009/08/skos-reference/skos.rdf . Wel moeten wel duidelijk de fresnel prefix gebruiken voor de URI's (classes en properties) uit de fresnel namespace. 

Bijvoorbeeld: owf:autocompleteOnClass rdfs:range fresnel:Format

Kan je dit regelen?

**Comment by LloydRutledge** [comment]
Over de naam: SF gebruikte ooit "autocomplete on ..." maar gebruikt nu blijkbaar "values from ..." met de oude waarschijnlijk nog ondersteund als deprecated hoewel die niet meer in de handleiding komt. SF blijft "autocomplete on ..." nog gebruiken in een parser function (forminput). We zouden dus "valuesFrom..." moeten gebruiken, maar values is meer van wiki forms velden en op het SW hebben we het over URI's of data objecten. Dus vind ik "autocompleteFrom..." (niet On) nu best als duidelijk, nog van toepassing in de nieuwe context, en nog wat woorden uit Semantic Forms.

**Comment by TeunTheunissen** [comment]
Ik heb aanpassingen gemaakt in de ontology zodat de termen niet aan de fresnel vocabulaire toegevoegd wordt.
Het is nu autoCompleteFrom geworden.
Nog een vraag voor dat ik de ontology ga commiten, ik heb een aantal ontologien bekeken en nergens zie ik staan waar de prefix voor de ontology geclaimd wordt. Waar definieren we dat onze ontology de prefix 'owf' heeft?

**Comment by LloydRutledge** [comment]
Bedoel je een soort centrale prefix registry? Er is wel http://prefix.cc/. "owf" staat er niet op. Ik weet niet hoe we het registreren.

Het is technisch niet nodig om die centraal globaal te registreren. Per RDF bestand zeg je welke namespaces en prefixes er zijn binnen dat bestand. Technische gezien zijn ze bedoel voor alleen binnen het bestand als een soort shorthand. Alleen de URI's werken globaal gebruikt.

**Comment by TeunTheunissen** [comment]
Ik heb de namespace aangepast. Zou je nog even willen controleren voordat ik het op de server zet.
Met name zie het commentaar, jouw email adres staat er, ben je het daarmee eens?
de website prefix.cc vraagt of je de prefix wil registreren als deze niet bestaat, zal ik dat doen?
vr.gr. Teun

**Comment by LloydRutledge** [comment]
Teun, kan je het regelen met prefix.cc nadat we over de details afspreken? Ik neem aan dat je Richard gewoon een e-mail stuurt. We kunnen hierover bij de scrum spreken. ik neem aan:

owf: http://is.cs.ou.nl/OWF/xxx#

maar dan "xxx" moet iet anders worden.

**Comment by jheijning** [comment]
Ik ga in ieder geval beginnen met een implementatie.

**Comment by TeunTheunissen** [comment]
prima, je kan gewoon de tag :autocompleteFromClass gebruiken zoals gedefinieerd in de fresnel_owf.owl ontology zie map "Environment & Misc\Ontologies\OWF"
succes

**Comment by jheijning** [comment]
Teun, kan je kijken of ik het zo goed gedaan heb alsjeblieft? zie de nieuwste revision. Zo ja, dan is er werk aan de winkel wat betreft de fresnel generatie en dan is dit ook gedaan :-)

**Comment by TeunTheunissen** [comment]
Joop, ik heb je wijzigingen gereviewed. De generatie naar wiki formaat gaat goed zover ik kan zien.
Je hebt de autocompleteFromClass gedefinieerd in de fresnel namespace, in de vorige scrum sessie met Lloyd bleek dat hij dat niet wou. Je zult het nu dus in de owf namespace moeten definieren.
dus owf:autocompleteFromClass i.p.v fresnel:autocompleteFromClass. 
Het lijkt mij dat je i.p.v. de FRESNEL vocabulairy class een nieuwe vocabulaire class definieerd met de naam OWF moet gebruiken. Als Alex het daarmee eens is natuurlijk.
vr.gr.TT

**Comment by jheijning** [comment]
Die OWF voc. class was er al :-) : autocompleteFromClass nu met OWF namespace.

**Comment by AlexMekkering** [comment]
GUI & Generic support for autocompletion has been implemented in r314.
I've implemented it as a slight variation of the proposed OWF autocompleteFromClass property:
- The plugin will always create an RDFList of Classes , for it may contain multiple ranges.
- On top of support for RDFLists as input, it also supports just a single Class (so not part of an RDFList) to correctly handle manually customized fresnel files.
- The method JenaFresnelUtils.getAutoCompleteFromClass will take a map of formattingProperties and retrieve a List of auto completion resources from it (may be empty), so this can be usefull for fresnel2wiki (See the unit tests).
- The GUI will mark autocompletion-enabled ObjectProperties with a trailing ~.

So, @TeunTheunissen, please adapt the OWF ontology to this, you can take a look at how the fresnel showProperties has been defined in http://www.w3.org/2004/09/fresnel#.

@jheijning, please review and have fun implementing the fresnel2wiki part :wink:

**Comment by jheijning** [comment]
Review OK, I had my fun implementing, now you review my code :-)

One thing: functional testing revealed that if autocomplete has been turned on for a property in a superclass (e.g. shakespeare ontology lit:Person, bio:married) then the same property in a subclass will have autocomplete turned on as well in the subclass in the wiki form (e.g. lit:Author bio:married) even though the subclass property has autocomplete turned off.

Is this according to requirements?

**Comment by TeunTheunissen** [comment]
Alex, zoals owf:autocompletefromClass nu is gedefinieerd bied het al de mogelijkheid om meerdere classes te definieren voor de autocomplete. Net zoals in de data ontology meerdere rdfs:range predikaten voorkomen zullen er dan meerdere owf:autocompletefromClass predicaten voorkomen, namelijk 1 voor elke range. Ik zal morgen kijken of ik dat kan inplementeren voor de 'save fresnel' knop. Vr.gr.Teun

**Comment by AlexMekkering** [comment]
Prima! De grootste uitdaging zit 'm dan echter in aanpassingen aan de helper methods in JenaFresnelUtils om fresnel2wiki te kunnen ondersteunen. Deze methoden zijn namelijk gebouwd rond het ontwerp dat properties later in de keten, dus met hogere prio, properties met lagere prio overriden.

Wanneer er voor een bepaald Format dan meerdere statements met dezelfde property als predicaat zijn, dienen deze gezamenlijk eerder gedefinieerde properties te overriden.
In de huidige situatie wordt dit eenvoudig ondersteund omdat owf:autocompletefromClass een RDFList als waarde kan hebben en er daardoor met één property beschrijving met één Object (nl. de RDFList, een anonieme Resource dus) een lijst van Classes kan worden toegekend. Het eventueel overriden van de owf:autocompletefromClass is dan eenvoudigweg het vervangen van een eerder gedefinieerde owf:autocompletefromClass.

In de situatie die jij voorstelt zou dus elk formatting Property een set van waarden moeten kunnen hebben welke overschreven kan worden door een set van waarden met hogere prio.

Dit zit 'm in de methoden:
- getFormattingProperties
- getAutoCompleteFromClass
- assembleProperties

Op zich ben ik het dus wel eens met je voorstel en implementatie in 'save fresnel' is denk ik eenvoudig, maar generieke ondersteuning, met name voor de gelaagdheid (specificiteit) in de Formats, heeft denk ik wat slimme aanpassingen hiervoor nodig. Wil je hier alvast ook even over nadenken? Dan kunnen we zondag in de skype meeting kijken wat de handigste methode hiervoor zal zijn.

**Comment by TeunTheunissen** [comment]
Dank voor de uitgebreide uitleg, ik ga de code bekijken.
Dan kunnen we deze zaak zondag bespreken.
Vr.gr.teun

**Comment by LloydRutledge** [comment]
@jheijning, je schreef:

"functional testing revealed that if autocomplete has been turned on for a property in a superclass (e.g. shakespeare ontology lit:Person, bio:married) then the same property in a subclass will have autocomplete turned on as well in the subclass in the wiki form (e.g. lit:Author bio:married) even though the subclass property has autocomplete turned off. Is this according to requirements? (ps. the same if you switch super/sub class)"

Kan je naar een voorbeeld verwijzen, zoals op je wiki? En/of de een link naar een bestand met de wiki code en ook de bron ontologie, en ook Fresnel-code als die niet default is?

Dit snap ik niet. Ik zie verschillende interpretaties van je beschrijving waarvan geen kloppen, maar misschien mis ik de juist interpretatie.

Heb je het over de default Fresnel of Fresnel die door de gebruiker aangepast is? Default Fresnel zal in de grote meerderheid van subclass relaties elke property toevoegen aan alleen één lens die de defaultLens voor de ketting van subclasses waarvoor die property een domain is. Zo heb ik geprogrammeerd in de OWF SMW extension PHP code, voornamelijk door SPARQL query's op een endpoint met RDFS reasoning. Dus in je voorbeeld de lens voor lit:Person zal de bio:married property hebben maar de lens voor lit:Author zal het niet hebben. Werkt het nu nog zo in de Protégé plugin?

Een reden waarom de Author lens ook married zou hebben is omdat het door de gebruiker expres toegevoegd is na de default. Is dat zo? Nog een is dat zelfs met mijn algorithm in PHP kan zowel een superclass als somigen van zijn subclasses hetzelfde property hebben als andere subclasses het niet hebben. Denk ik. Ik ben dus benieuwd naar de details from je bron code.

Maar toch zou het moeten kunnen dat een superclass en property met autocompletion heeft en een subclass dezelfde property heeft maar dan zonder autocompletion. Volgens mijn werkt dat nu niet omdat elke property alleen één format kan hebben ongeacht van op welke lens het gebruikt wordt. We hebben ooit in een scrum gesproken over hoe we eigenlijk elke property format moeten noemen voor niet alleen de property maar ook zijn context, zoals in dit geval zijn lens of class. Dan heb je een aparte format voor de property-lens combinatie, en dus heeft een property verschillende formats op verschillende lenses.

Klopt dit laatste uitleg? Is het dan nuttig om het zo te implementeren? Of nuttig maar te veel werk?

**Comment by jheijning** [comment]
Voorbeeld:

![captura](https://cloud.githubusercontent.com/assets/9306134/6094357/7abfcec6-af27-11e4-98ad-82564b5fd0da.PNG) 
Dit is default Fresnel van http://www.workingontologist.org/Examples/Chapter3/shakespeare.owl , waarbij ik in lit:Person de property bio:married Auto Complete heb gegeven.

---Dit is uit de wiki-export Form:lit-Person, met zoals verwacht autocompletion op bio:married:
! married: 
| {{{field|married|autocomplete on category=Person|list }}}
|- 
! livedIn: 
| {{{field|livedIn|list }}}
|- 
! hasChild: 
| {{{field|hasChild|list }}}

---En dit is uit Form:lit-Author:
| {{{field|wrote|list }}}
|- 
! married: 
| {{{field|married|autocomplete on category=Person|list }}}
|- 
! livedIn: 
| {{{field|livedIn|list }}}

Antwoord op je laatste vraag, of het nuttig maar te veel werk is, kunnen @AlexMekkering en @TeunTheunissen  beter antwoord op geven.

**Comment by AlexMekkering** [comment]
@jheijning: Wat een geweldige functionele bevinding :+1:.
Ik heb er even over gedaan om deze te analyseren, maar dit was het gevolg van het volgende:
- Een property van een Lens, welke specifieke formattering voor die Lens heeft, wordt middels een propertyDescription expliciet gekoppeld aan een specifiek Format.
- Formats met een fresnel:propertyFormatDomain zijn impliciet van toepassing op een property.
- Voor een expliciet gedefinieerde Format, werd bij het creeren van de fresnel ontologie echter ***ook*** een fresnel:propertyFormatDomain gedefinieerd. Hierdoor werd de Format, welke slechts van toepassing zou moeten zijn op de specifieke property op die lens, ***ook*** van toepassing op de property in het algemeen, wat natuurlijk niet de bedoeling is.

Ook dit probleem is een voortvloeisel uit de 'oude' MDDFresnel plugin, waar het genereren van de fresnel ontologie al op deze manier gedaan werd.

Ik heb de oplossing hiervoor, welke bestaat uit het verwijderen van één regel code welke de fresnel:propertyFormatDomain definieerde, gecommit in r323. Wil jij 'm nog even reviewen?

**Comment by AlexMekkering** [comment]
##### Review van commit r319

In het algemeen doet de code wat het moet doen, dus :+1:.

Met het oog op schaalbaarheid zouden echter de formatting Properties het best slechts eenmalig per property/lens bepaald kunnen worden, dat is ook de reden waarom deze doorgegeven worden aan de methode JenaFresnelUtils.getAutoCompleteFromClass. Op dit moment wordt namelijk JenaFresnelUtils.getFormattingProperties een aantal malen aangeroepen om de formatting Properties te bepalen waardoor telkens de gehele fresnel ontologie doorzocht moet worden.
Er wordt al wel een versie van de formatting Properties bewaard, maar deze wordt voor bijv. het bepalen van de delimiter niet gebruikt. Ook de methode getCSS (welke meerdere malen wordt aangeroepen) bepaalt zelf weer wat de formatting properties zijn.

Een oplossing hiervoor zou dus kunnen zijn dat de aanroep naar JenaFresnelUtils.getFormattingProperties per property voor een lens, eerder in het proces wordt gedaan, en het resultaat ervan (een HashMap) doorgegeven wordt aan getCSS en gebruikt wordt voor het bepalen van alle formatting properties.

**Comment by jheijning** [comment]
Review van commit r323: Goed!

Dank je voor je interessante commentaar op de review. Ik zet het bij #49 

Dus dan kan deze gesloten worden wat mij betreft.

**Comment by AlexMekkering** [comment]
@LloydRutledge, je screef:
Heb je het over de default Fresnel of Fresnel die door de gebruiker aangepast is? Default Fresnel zal in de grote meerderheid van subclass relaties elke property toevoegen aan alleen één lens die de defaultLens voor de ketting van subclasses waarvoor die property een domain is. Zo heb ik geprogrammeerd in de OWF SMW extension PHP code, voornamelijk door SPARQL query's op een endpoint met RDFS reasoning. Dus in je voorbeeld de lens voor lit:Person zal de bio:married property hebben maar de lens voor lit:Author zal het niet hebben. Werkt het nu nog zo in de Protégé plugin?

In de plugin wordt aan Protégé gevraagd om de domain classes van een bepaalde property te geven. Voor elke domain class die Protégé teruggeeft wordt dan de property toegevoegd aan de default Lens voor die klasse. Op zich lijkt me dit correct.

Wat ik eigenlijk nog niet goed snap is waarom Protégé, zonder reasoning geactiveerd, aangeeft dat 
bio:married een objectProperty met domain lit:Author zou zijn. Volgens de [Shakespeare ontologie](https://github.com/ABI-Team-30/Fresnel-Forms/blob/master/Ontologies/shakespeare.n3) is deze namelijk slechts gedefinieerd als objectProperty met domain lit:Person, waarvan lit:Autor een subklasse is.

Dus... nader onderzoek volgt nog...

**Comment by TeunTheunissen** [comment]
range-list probleem staat nog open.

**Comment by AlexMekkering** [comment]
Na aanpassen van het unit-test fresnel bestand waarbij fresnel:propertyFormatDomain verwijderd was bij expliciete formaten, bleek dat de oplossing van r323 niet voldoende was. Voor het inlezen van formaten voor properties werd namelijk gekeken naar alle formaten met het betreffende propertyFormatDomain, welke voor expliciete formaten dus niet meer aanwezig hoeft te zijn.

De oplossing hiervoor is gecommit in r333.
Hierbij wordt dankbaar gebruik gemaakt van de helper methode getFormattingProperties (waarbij de Groups overgeslagen worden omdat die al bij het inlezen van de Lens behandeld zijn). Op deze manier worden voor een property op een lens altijd de meest specifieke formatting properties aan de PropertyBinding gekoppeld.
Ook is hiermee de klasse PropertyBindings overbodig geworden welke een formatting property kon toepassen op meerdere PropertyBinding(s).
Eigenlijk werkt het bepalen van formatting properties nu precies andersom: waar eerder alle formaten langs werden gelopen en gekeken voor welke properties ze van toepassing zijn, worden nu voor elke lens alle properties langsgelopen en de meest specifieke formatting properties ervoor bepaald. Het overslaan van de formatting properties in de Groups is hier van groot belang omdat die properties voor de Lens zelf gelden en in de GUI ook alleen daar terecht moeten komen, dus niet als eigenschappen van de afzonderlijke properties op die Lens.

@TeunTheunissen, zou jij de wijzigingen in commit r333 nog aan een review willen onderwerpen? Functioneel is er dus eigenlijk slechts ondersteuning voor expliciete Formats bijgekomen welke geen fresnel:propertyFormatDomain hebben, maar 'under the hood' is het toch behoorlijk veranderd.

**Comment by AlexMekkering** [comment]
Ondersteuning voor meerdere definities van een property met dezelfde prioriteit is toegevoegd in r337.

De methode getFormattingProperties geeft nu een PropertyMap terug, welke een afgeleide klasse is van HashMap<Resource, List<RDFNode>>. Er wordt dus nu niet één RDFNode per property teruggegeven, maar een List van RDFNodes per property.
Doordat PropertyMap afgeleid is van een Map ondersteunt het dus alle methoden ervan (zoals .get(<resource>)) maar daarnaast is ook een pick(<resource>) methode gedefinieerd welke een arbitraire RDFNode uit de lijst teruggeeft. Het gedrag van de pick pethode is dus ongeveer gelijk aan die van de get methode voorheen.

In het algemeen kun je nu:
- `PropertyMap.get(<property>)` gebruiken om lijsten van meest specifieke waarden van properties te bepalen. Dit is handig voor bijv. owf:autocompleteFromClass properties die in principe meerdere keren kunnen voorkomen per Format.
- `PropertyMap.pick(<property>)` gebruiken om een enkele waarde (RDFNode) van een property te bepalen. Dit is handig voor de meeste andere gevallen omdat in de meeste gevallen properties slechts eenmalig gedefinieerd zijn binnen een Format (zoals fresnel:propertyStyle, etc.).

De overige functionaliteit is nog hetzelfde gegeven, dus:
- Meer specifieke properties overschrijven minder specifieke properties (minder specifieke lijsten van RDFNodes worden vervangen door specifiekere).
- Styling properties (CSS) worden nog steeds geprioriteerd geconcateneerd.

@TeunTheunissen, zou je de wijzigingen van r337 mee kunnen nemen in de review?

Voor #42 wordt het owf:datatype nu op dezelfde manier behandeld als owf:autocompleteFromClass bij dit issue, dus er worden (op show- en hideProperties na) geen RDFLists meer gebruikt, maar er is nu algehele ondersteuning voor meermalig gedefinieerde properties. Op deze manier sluit dit ook naadloos aan op RDF.

**Comment by TeunTheunissen** [comment]
review r333: De code ziet er goed uit een paar kleine opmerkingen over de documentatie van methode 
fillLensShowPropertiesFromResources:
- Het attribuut fresnelheeft geen @param javadoc in de javadoc header.
- In de code nog iets van commentaar graag, zoals in de methode 'formatPropertyBinding'.

r337:
- in de classe FresneltoWiki: 
  de private methoden hebben geen javadoc zou wel moeten. Misschien iets voor Joop.

vr.gr. Teun

**Comment by jheijning** [comment]
Officiëel hoeven alleen public methoden Javadoc, maar het zou inderdaad wel netjes zijn voor reviewers en toekomstige abiteams om wel tenminste minimale javadoc toe te voegen. Ik maak er een minor issue van.

**Comment by AlexMekkering** [comment]
Reviewcommentaar verwerkt in r340.
Wat mij betreft kunnen we deze dus eindelijk echt sluiten :smile:. Vervolgwerkzaamheden vinden plaats in met name #42 en $49.
