### ISSUE TITLE
Formatted properties worden niet goed naar SMW vertaald.

### ISSUE THREAD

**Issue by AlexMekkering** [ABI-Team-30/Fresnel-Forms#31]
Bij het converteren van Fresnel naar SMW (zie #7) worden formatted properties niet goed meegenomen.
Formatted properties kun je herkennen aan een anonieme node (in showProperties) met als rdf:type fresnel:propertydescription.
Is de naam van de formatted property in dat geval de waarde van fresnel:property van die node of de waarde van fresnel:label van het Format welke beschreven is met fresnel:use?

**Comment by jheijning** [comment]
Ik ga het nog eens goed functioneel testen, maar het lijkt opgelost te zijn met de nieuwe jena tussenlaag. Indien de test succesvol: sluit ik hem.

**Comment by jheijning** [comment]
Test was succesvol.
