### ISSUE TITLE
Nieuwe data of object property wordt niet meegenomen in de default Fresnel.

### ISSUE THREAD

**Issue by TeunTheunissen** [ABI-Team-30/Fresnel-Forms#32]
Usecase: Nadat een default Fresnel diagram is gegenereerd wordt een nieuw data of object property aan de ontology toegevoegd in Protege. Daarna wordt opnieuw op de knop "Default Fresnel" geklikt. De nieuwe data/object property verschijnt niet in het default fresnel diagram.

**Comment by AlexMekkering** [comment]
Opgelost in r233. Aangezien dit op de ontologie gefocussed is, mag @TeunTheunissen deze reviewen.

Uit een korte analyse van de code bleek het volgende:
* De bronontologie wordt niet rechtstreeks gebruikt voor de invulling van de GUI; Door de OWLImport klasse wordt er een pseuso-ontologie gecreëerd (zie ontology package) waarmee de lenzen, data- en objectproperties gecreëerd worden. 
* De import vanuit de OWLImport klasse werd slechts bij het initialiseren van de View (binnen Protégé) uitgevoerd en sinds implementatie van #11 ook bij het wisselen van actieve ontologie.

De oplossing was dus om de bronontologie opnieuw te laten importeren (door een nieuw controller object te definiëren).

**Comment by TeunTheunissen** [comment]
Werkt weer als een trein. keurig van commentaar voorzien.
Review is OK.
