### ISSUE TITLE
wiki export bestandsnaam zonder extensie

### ISSUE THREAD

**Issue by jheijning** [ABI-Team-30/Fresnel-Forms#33]
Zojuist code toegevoegd zodat een bestandsnaam automatisch de .n3 extensie krijgt indien de gebruiker zelf geen extensie heeft toegevoegd.

Er waren ook libraries voor, maar die zaten niet in het project, dus maar op de ouderwetse manier gedaan. Zie: http://stackoverflow.com/questions/3571223/how-do-i-get-the-file-extension-of-a-file-in-java

**Comment by TeunTheunissen** [comment]
Ha Joop, de code is prima, ik heb ook de libraries bekeken voor de file extensie en het lijkt mij wat zwaar geschut voor onze 'onderzoek toepassing'. Het lijkt me wel noodzakelijk om het lijstje 'files of type' in de save dialog uit te breiden met 'xml' en dit type default te maken, Hierdoor laat de save dialog automatisch alle bestaande xml files zien en het is de gebruiker duidelijk dat de wiki als xml bestand bewaard moet worden. Het is technisch een kwestie van de FresnelFileFilter classe copieren en aanpassen daarna de getfiletype methode aanpassen.
Vr.gr.Teun

**Comment by AlexMekkering** [comment]
org.apache.commons.io is wel een veel gebruikte en algemene library, maar ik ben het ermee eens dat dit voor alleen deze oplossing wat zwaar geschut zou zijn om mee te nemen in alle afhankelijkheden.

**Comment by TeunTheunissen** [comment]
Ik bekeek net revisie 238, voor issue #34, daar zag ik deze import: -import com.hp.hpl.jena.util.FileUtils;
De classe FileUtils heeft een methode getFilenameExt.
De library Jena hebben we toch al geladen dus ik stel voor om deze methode te gebruiken ipv zelf iets te hacken.

**Comment by AlexMekkering** [comment]
Uitstekend opgemerkt! Had ik zelf nog niet aan gedacht, maar lijkt me een mooie oplossing die we voor meer zaken kunnen gebruiken.

**Comment by jheijning** [comment]
Goede opmerkingen, ik ga er naar kijken.

**Comment by jheijning** [comment]
@TeunTheunissen Ik had tot nu toe niet eens in de gaten dat saveFresnel met FresnelFileFilter eigenlijk al doet wat ik wil. Nu doet saveWiki hetzelfde maar beter en compacter volgens mij, met de Jena FileUtils getFilenameExt zoals je aanraadde en fc.setFileFilter(new FileNameExtensionFilter(".xml", "xml"));  de saveFresnel heb ik laten staan zoals het is.

**Comment by jheijning** [comment]
teun: alsjeblieft review

**Comment by TeunTheunissen** [comment]
Review gedaan, code is lekker compact en het werkt als een tierelier.
Review=OK.

**Comment by jheijning** [comment]
Ja mijn fout, ik heb saveFresnel weer gelaten zo als het was toen ik die fresnelfilefilter klasse ontdekte, maar die werkt dus toch niet, dus ook saveFresnel heeft nu exact dezelfde oplossing als saveWiki. Misschien kan Teun nog een blik werpen op die paar regels code daarvoor. Heb het zelf functioneel getest, werkt net zoals saveWiki..

**Comment by TeunTheunissen** [comment]
ziet er prima uit en het werkt zoal het moet werken.
review OK.
