### ISSUE TITLE
NullPointerException bij FOAF saveFresnel en saveWiki in de plugin

### ISSUE THREAD

**Issue by jheijning** [ABI-Team-30/Fresnel-Forms#34]
"Het lijkt te maken te hebben met het bepalen van de default prefix van de bronontologie."

NullPointerException: null URIs are prohibited as arguments to setNsPrefix
    com.hp.hpl.jena.shared.impl.PrefixMappingImpl.setNsPrefix(PrefixMappingImpl.java:69)
    com.hp.hpl.jena.rdf.model.impl.ModelCom.setNsPrefix(ModelCom.java:982)
    fresnelio.FresnelManager.fromFresnel(FresnelManager.java:165)
    main.Controller.saveWiki(Controller.java:103)
    view.FresnelFormsViewComponent$4.actionPerformed(FresnelFormsViewComponent.java:96)
    javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
   …
 
NullPointerException: null URIs are prohibited as arguments to setNsPrefix
    com.hp.hpl.jena.shared.impl.PrefixMappingImpl.setNsPrefix(PrefixMappingImpl.java:69)
    com.hp.hpl.jena.rdf.model.impl.ModelCom.setNsPrefix(ModelCom.java:982)
    fresnelio.FresnelManager.fromFresnel(FresnelManager.java:165)
    fresnelio.FresnelManager.save(FresnelManager.java:126)
    main.Controller.saveFresnel(Controller.java:81)
    view.FresnelFormsViewComponent$1.actionPerformed(FresnelFormsViewComponent.java:57)
    javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
   …

**Comment by LloydRutledge** [comment]
Alex als assignee want hij is de Protege-fundament goeroe (?)

**Comment by LloydRutledge** [comment]
Joop: tot hoever is deze een absoluut blokkade bij het werken met FOAF? FOAT is nodig voor de Forms paper

**Comment by jheijning** [comment]
Ik denk 100%, wat je kunt zo niet FOAF Fresnel of Wiki exporteren.

**Comment by LloydRutledge** [comment]
Ik maak deze dan een "Must"

**Comment by AlexMekkering** [comment]
Solved in r238.

Probleem was dat foaf geen default prefix heeft (natuurlijk wel een foaf: prefix). De oplossing bestaat nu uit het importeren van ALLE prefixes uit de bronontologie en het vervangen van een eventuele default prefix (:) door de naam van de ontologie, zoals het eerder ook gedaan werd.
Hierdoor wordt gelijk ondersteuning geboden voor alle andere eventueel aanwezige prefixes in de bronontologie :smile:. Nadeel is dat de lijst met prefixes (gebruikt of niet gebruikt) in het fresnel bestand langer wordt.

Vanwege de focus op de ontologiekant, mag @TeunTheunissen het weer reviewen.

**Comment by AlexMekkering** [comment]
Refactored and simplified in r239 to solve checkstyle issues. Please take this into account also.

**Comment by TeunTheunissen** [comment]
Vanuit de ontology kant is het natuurlijk niet zo fraai dat er namespaces staan gedefinieerd die niet gebruikt worden. Functioneel kan het geen kwaad en daarom lijkt het me alleen de moeite waard om dit aan te passen als het niet al te veel werk is. Ik ga nog even kijken naar de code.

**Comment by TeunTheunissen** [comment]
Over de code zelf kan ik niet zoveel zeggen behalve dat het er OK uitziet en dat het werkt!!
So, well done.
Wat de documentatie betreft zou de jdoc aanhef bij methode prepareNewModel wat specifieker kunnen, * Prepares the internal (Apache Jena) model, according to the reference model and the given fresnel ontology.
zover ik het begrijp wordt in deze methode enkel de prefixes uit de bron ontology ingelezen in het jena model. Dus i.p.v. 'Prepares' iets als 'Read and add the prefix definions..
De methode  'fillPropertyBindingsFromResource' heeft enkel javadoc en geen commentaar in de code die aangeeft wat het doel van de code is.
Vr. gr. Teun

**Comment by AlexMekkering** [comment]
Mee eens. Bijgewerkt in r245
