### ISSUE TITLE
fresnel:label fresnel:none ondersteuning toevoegen

### ISSUE THREAD

**Issue by AlexMekkering** [ABI-Team-30/Fresnel-Forms#35]
Voor #27 is ondersteuning nodig om een label niet te tonen. Dit wordt nu niet ondersteund.

**Comment by AlexMekkering** [comment]
Algemene ondersteuning is ingebouwd in r252.
De benodigde aanpassingen voor de GUI volgen nog. Tot die tijd kan het gebruikt worden door in een gegenereerd fresnel bestand het fresnel:label van de betreffende property handmatig met bijv. notepad++ de waarde fresnel:none te geven (zie ook de aanpassingen voor de unit tests in src/test/resource/TheFirm.fresnel).

Wat mij betreft nu dus niet meer blocking...

**Comment by AlexMekkering** [comment]
GUI ondersteuning is inmiddels ook aanwezig, dus ik draag hierbij het stokje over aan @jheijning voor het meenemen in de conversie naar de wiki output.
Wil je dan ook gelijk mijn implementatie reviewen?

**Comment by jheijning** [comment]
Ik heb een beginnetje gemaakt met de conversie, zie methode hidePropLabel() in Fresnel2wiki. Het werkt wel als ik fresnel:none invul in bv. :indirectlyContractsToFormat , maar het moet natuurlijk zoeken in :indirectlyContractsToPersonLensFormat. Ik zal Alex en Teun om raad vragen in een volgende teamvergadering.

**Comment by jheijning** [comment]
en Alex' implementatie reviewed en goed bevonden.

**Comment by jheijning** [comment]
Respect voor Alex voor de Jena tussenlaag :+1: 
Met gebruik van de nieuwe help-methode. 
Review alsjeblieft.

**Comment by AlexMekkering** [comment]
Net als #37, maakt de code netjes gebruik van JenaFresnelUtils.
De output lijkt ook goed te zijn, al weet ik zo niet hoe ik dat kan testen op onze server. Ik heb succesvol een import kunnen uitvoeren van een TheFirm output, maar weet zo niet waar ik dan die hidden label kan verifiëren.
Heb jij ideeën @jheijning?

**Comment by jheijning** [comment]
In Protégé FF selecteer je dus een property met hide label. Dan na import op de wiki ga je naar Form:Person en vult de waardes in en dan bekijk je de bewerkingen. Dan zal het label van de property met hidden label hidden zijn en de waarde in het midden van de box.
