### ISSUE TITLE
Define proxy Jena model with fresnel utility functions to relieve fresnel2wiki from fresnel semantics.

### ISSUE THREAD

**Issue by AlexMekkering** [ABI-Team-30/Fresnel-Forms#36]
To simplify implementation of fresnel2wiki, we should create helper functions for fresnel semantics.
These fresnel semantics will be applied to the Jena model, so a Jena (Proxy) class for providing these helper functions will suffice.

A first candidate for a helper function will be one that returns a list of most specific Format properties for a specific Property and a Lens (which can be absent (null).
This method will check all Formats which apply to a Property and an optional Lens. The specificity of Formats is defined as follows (with increasing specificity):
- Format with fresnel:propertyFormatDomain <property> and without fresnel:Group which is equal to the Group to which the provided Lens belongs.
- Format with a fresnel:Group which is equal to the Group to which the provided Lens belongs and without fresnel:propertyFormatDomain <property>.
- Format with fresnel:propertyFormatDomain <property>and a fresnel:Group which is equal to the Group to which the provided Lens belongs.

A second candidate for a helper function will be one that returns only showns properties (so properties which are defined in fresnel:showProperties, but not in fresnel;hideProperties.

**Comment by AlexMekkering** [comment]
Implemented in r268 and r269:
- In r268 the classes and package are restructured and a JenaFresnelModel is extracted from the FresnelManager (its only task now is coupling of the Fresnel model with the Jena (RDF) model).
- In r269, extra helper methods are added, implementing fresnel semantics. For now, the following methods are available:
 - getPropertiesToDisplay - retrieves all properties to display for a lens, so hidden properties will not be part of the results of this method. It also takes property descriptions into account; the properties they describe will be returned instead of the property description itself.
 - getFormattingProperties - Determines the formatting properties of a property for a lens by prioritizing all applicable Formats (For every formatting property, only the most specific one will be part of the results of this method).

There are also some more trivial helper methods (helping the helper methods described above :smile:), so please check the JavaDoc.

@jheijning, can you review this? Changes in r268 seem to be quite a lot, but the real changes are quite limited, though a lot has been restructured.

**Comment by jheijning** [comment]
In JenaFresnelModelTest you construct testLens with related properties. I haven't been able to replicate the test with the domain variable in Fresnel2wiki.execute() (to replace the makePropertiesList(domain) method. Probably I just do not understand something correctly.

For the rest code review looks good.

**Comment by jheijning** [comment]
Two hours later: Eureka! I was using domains instead of lenses, that's why jenaFresnelModel.getPropertiesToDisplay(lens); didn't work. Now everything looks a lot tighter!

**Comment by jheijning** [comment]
if it's up to me: closed!
