### ISSUE TITLE
Hidden properties still show up in wiki output

### ISSUE THREAD

**Issue by jheijning** [ABI-Team-30/Fresnel-Forms#37]
Properties that are set to "hide" in the gui should not be exported to the wiki form and informbox.

**Comment by jheijning** [comment]
Fixed with a double SPARQL query (one for hidden properties). Please review Alex.

**Comment by AlexMekkering** [comment]
Samen met #35 gereviewed aangezien een commit hiervoor de double SPARQL query onnodig maakte. Netjes opgelost en efficiënt gebruik gemaakt van de JenaFresnelUtils tussenlaag!
Functionele tests leveren ook de juiste uitkomst, dus... :+1:
