### ISSUE TITLE
Relabeled properties' labels moeten naar wiki worden geëxporteerd

### ISSUE THREAD

**Issue by jheijning** [ABI-Team-30/Fresnel-Forms#38]
Nu wordt de "localName" nog als label naar de form/informbox geëxporteerd, moeten de fresnel:label waarden worden. Zodra Alex' zijn nieuwe Jena tussenlaag heeft ga ik naar kijken.

**Comment by jheijning** [comment]
Teun, review alsjeblieft. Maar een paar regels code.

**Comment by TeunTheunissen** [comment]
Code is OK, export is OK. ik heb de ancestry ontology gebruikt, sweet and simple. de engelse labels zijn aangepast naar nl zie en dat zie ik terug in de wiki export: [[Property:hasAncestor|Heeft voorouder]]
Vraag: hoe importeer ik dat in de semantic wiki? Als ik een rdf import doe krijg ik een foutmelding.

**Comment by jheijning** [comment]
special:import en dan gewoon het wiki export xml bestand selecteren.
