### ISSUE TITLE
Propertie definitie in fresnel extensie 'IsList' default true 

### ISSUE THREAD

**Issue by TeunTheunissen** [ABI-Team-30/Fresnel-Forms#39]
In de fresnel_owf ontology een uitbreiding maken waarmee aangegeven kan worden of multi values toegestaan zijn voor een property of niet. Standaar zijn multivalues toegestaan.

**Comment by LloydRutledge** [comment]
Gebruik de namen en structuur van de Semantic Forms syntaxis en parameters op http://www.mediawiki.org/wiki/Extension:Semantic_Forms/Defining_forms als basis. Handig als je een mapping hebben van die naar je ontologie. Hierbij bijvoorbeeld kijk naar http://www.mediawiki.org/wiki/Extension:Semantic_Forms/Defining_forms#Multiple_values_for_the_same_field en http://www.mediawiki.org/wiki/Extension:Semantic_Forms/Semantic_Forms_and_templates#Multiple_values_for_the_same_field

**Comment by TeunTheunissen** [comment]
Opgelost in issue  'OWL-lite cardinality <=> 0/1 #47'
