### ISSUE TITLE
Propertie definitie in fresnel extensie: delimiter definitie voor een property 

### ISSUE THREAD

**Issue by TeunTheunissen** [ABI-Team-30/Fresnel-Forms#40]
De delimiter definieerd het koppel tekens tussen de multivalues. kan een streep, komma, crlf zijn.

**Comment by LloydRutledge** [comment]
Lees http://www.mediawiki.org/wiki/Extension:Semantic_Forms/Semantic_Forms_and_templates#.5Cn_delimiter voor newline. En de delimiter veld in http://www.mediawiki.org/wiki/Extension:Semantic_Forms/Semantic_Forms_and_templates#arraymap

**Comment by AlexMekkering** [comment]
Added generic & GUI support in r297. Added owf:delimiter to the OWF vocabulary for this.

@TeunTheunissen, please review.
@jheijning, you can retrieve OWF.DELIMITER from getFormattingProperties now for wiki implementation.

**Comment by AlexMekkering** [comment]
FYI, Wanneer de delimiter gelijk is aan de default (nu ', ') dan wordt deze niet opgeslagen en is derhalve ook niet aanwezig in getFormattingProperties()...

**Comment by jheijning** [comment]
Ook geïmplementeerd in fresnel2wiki, bij een functionele test werkt deze van gui tot de testwiki. Kijk bijvoorbeeld naar test1 op de testserver. @TeunTheunissen nu je toch bezig bent met reviewen van Alex' code voor dit issue, kun je dan meteen die van mij reviewen :-)? #40

Btw. tot zondag neem ik even pauze van het project, maar zal emails wel proberen te beantwoorden.

**Comment by TeunTheunissen** [comment]
Yep ik zal dit issue reviewen.

**Comment by TeunTheunissen** [comment]
@Alex: review functionaliteit is OK, en de code ook. 
opmerking: in PropertyLabelRightClickMenu, de teksten voor de menu's en JOptionPane.showInputDialog zijn opgenomen als magic strings, waarom niet als constante in de classe opnemen? Merkwaardig is dat checkstyle er geen melding van geeft.

**Comment by TeunTheunissen** [comment]
@Joop: wat opmerkingen:
mvn clean install levert een error op.

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.559 sec <<< FAILURE! - in fresneltowikitest.FresnelToWikiTest
testFresnelToWiki(fresneltowikitest.FresnelToWikiTest)  Time elapsed: 0.559 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at fresneltowikitest.FresnelToWikiTest.testFresnelToWiki(FresnelToWikiTest.java:101)



regel 101 in FresnelToWikiTest.java uitgecommentarieerd en het compileerd weer.
		assertTrue(containsString(PERSON_BOX_PAGE, "text-align:left;color:yellow; color:purple;\""));

Ik heb regel 101 uitgecommentarieerd en daarna een build gemaakt en die getest.
De test heb ik gedaan met de shakespeare.owl ontologie.
Geen wijzigingen daarna een 'save wiki' levert een arraymap op waar geen delimiter is gedefinieerd. is OK
Als ik in de gui de default kies ', ' staat er niets gedinieerd in de arraymap functie.
Lijkt me ook OK.

Als ik voor de property livedIn instel delimiter ' - ' dan geeft een save: {{#arraymap:{{{livedIn|}}}|,|xxx|[[livedIn::xxx]]}}
Lijkt me niet OK.

V.r gr. teun

**Comment by AlexMekkering** [comment]
Voor die falende unit test: zie Review commentaar #5.

**Comment by jheijning** [comment]
Teun, zie pagina http://abiteam30.lukylx.org:3080/mediawiki/index.php/TestShake . ook met - en livedIn, het werkt bij mij.

Ik zie in de geschiedenis ook geen import van jou op de testwikiserver, het lijkt er op dat jouw import niet gewerkt heeft en dat daarom jouw test niet werkte. Kun je nog een keer kijken alsjeblieft?

**Comment by AlexMekkering** [comment]
Refactoring uitgevoerd en verschillende Checkstyle meldingen opgelost en unit tests weer laten slagen.
De magic strings die je aangeeft heb ik echter niet aangepast en wel om de volgende redenen:
- De strings hebben geen referentieel doel. Het zijn slechts de invullingen van titels, berichten etc. Het creëren van constanten op klasseniveau zou het mijns inziens dan alleen maar onduidelijker maken en onnodig veel klasse-attributen toevoegen die verder niet echt van belang zijn.
- Checkstyle heeft, in tegenstelling tot voor magic numbers, geen regel die zegt dat literal strings bad practice zijn. Volgens http://checkstyle.sourceforge.net/config_coding.html kent het wel een melding voor MultipleStringLiterals welke aangeeft dat meerdere dezelfde literals beter op één plaats (bijv. constante) gedefinieerd kunnen worden, maar daar is hier geen sprake van.

Dus... zolang Checkstyle niet klaagt vind ik het dus eigenlijk wel best zo.

**Comment by TeunTheunissen** [comment]
@AlexMekkering : prima, mee eens.we laten het zo.
@jheijning Ik heb een update gedaan van de sourcecode, revisie 308, een nieuwe build gemaakt en nu gaat de tests goed en de save fresnel gaat ook goed in de array functie staat keurig ' - ' maar dan zonder de quotes. De import lijkt ook goed te gaan, de pagina's die aangemaakt worden met categorie lit-person krijgen voor livedin ook een '-'als scheidings teken.
Dit issue kan gesloten worden.
