### ISSUE TITLE
Hidden Lenses to Export

### ISSUE THREAD

**Issue by jheijning** [ABI-Team-30/Fresnel-Forms#41]
Teun, we haven't talked much about this, so I call it a should for now. But in the Gui there is already an option for it. It would probably not be too hard for me to implement it in fresnel2wiki once it is in Fresnel.

**Comment by LloydRutledge** [comment]
Wat zou een hidden lens zijn in wiki code?

**Comment by jheijning** [comment]
Als je in de GUI rechtermuisknop op een property klikt en "Hide" selecteert, dan heb ik het zo geïmplementeerd dat deze property helemaal niet in de wiki-export wordt meegenomen (hij blijft dus alleen in het fresnel bestand staan in de lijst fresnel:hiddenproperties () van een lens).

Dus dat was ook mijn idee om het zo te doen als iemand in de GUI rechtermuisknop klikt op een lens en "hide" selecteert. Dat de lens helemaal niet wordt meegenomen in de GUI export.

In het geval dat de ontwerper op de GUI wel Free Text mogelijk wil maken maar alleen de informbox wil verbergen, kan hij natuurlijk de Lens gewoon op "show" laten staan, maar in het CSS resourcestyle-veld gewoon "diplay:none;" invullen.

Is dat goed?

**Comment by TeunTheunissen** [comment]
Ha Joop, ik heb de default fresnel van de shakespeare ontology met een hidden lens bewaard. In het bestand staat die lans dan ook niet. Daarna heb ik de lens weer 'shown' gezet en voor de css resourcestyle display:none ingevuld en bewaard. Dit staat keurig in het bewaarde fresnel bestand.
Dus het fresnel model in de protege plugin heeft deze opties al en je zou ze dus moeten kunnen uitlezen bij je conversie van fresnel naar wiki code. Ik snap dus niet helemaal wat je van mij verwacht.
Groeten Teun

**Comment by jheijning** [comment]
Dat is dan een meevaller :) dan heb ik op dit punt van jou niets verder nodig inderdaad.

**Comment by LloydRutledge** [comment]
Is een hidden lens iets anders dan hidden properties? Wat in Fresnel maakt een hele lens hidden?

**Comment by LloydRutledge** [comment]
Fresnel heeft hidden properties en geen hidden lensen. Maar de plugin heeft dan wel hidden lensen waardoor de gebruiker zegt dat een lens (waarschijnlijk van de default gen) bewaard maar niet getoond wordt. En Teun, begrijp ik het nu goed dat dit opgeslagen als "display:none" wordt, en daardoor wordt het uitgevoerd wordt door elke Fresnel toepassing. Een beetje hacky, maar slim. Als het Fresnel bestand later inlezen wordt, is het door deze display:none CSS dat de plugin herkent dat de lens hidden is? Of is er andere syntaxis voor? Of werkt het niet?

**Comment by LloydRutledge** [comment]
Joop, kunnen we de hidden lenses gewoon negeren in de wiki export? Je voorstel zou in princiep werken voor pagina's waarop de template van die lens staat. Ik kan het wel voorstellen tussen andere pagina inhoud. Maar het zou raar zijn als enige inhoud van een pagina, waardoor de pagina als leeg toont.

Nog raarder is dat er een Form: en Template: pagina op de wiki zou komen voor iets dat nooit toont. De Form zou dan op de lijst van forms komen, waardoor de gebruiker op die zou klikken om een nieuwe pagina te starten door die form om in te vullen. Ziet ie dan deze Form van de hidden lens? Vult hij dan gegevens in en dan slaat hij die op alleen om een pagina dan te zien die niks toont? Ik zie er geen user story voor.

De user story dat ik zie is deze: De gebruiker krijgt een default Fresnel. Enkele lensen wilt hij niet in de interface hebben maar wilt die toch bewaren voor mogelijke later gebruikt. Die worden dus hidden lenses. Later zou hij dit bestand inlezen en die makkelijke unhidden maken als hij die terug wilt. Maar voorlopig wilt hij die bepaald niet in de interface hebben. Is zie geen nut en mogelijke verwarring als die hidden lensen in de wikicode komen. Het hele nut van hidden lenses is om die later makkelijke terug te kunnen krijgen, en die nut bereik je in de plugin, niet in de wiki.

Is het dus meest zinvolle om de hidden lenses niet in de wiki te brengen?

**Comment by jheijning** [comment]
De :display:none is alleen een CSS stijl die een ontwerper in de gui kan invullen, net zoals hij kan invullen color:blue, daar doet onze code niets mee, behalve dat het doel is om alles wat de ontwerper in de CSS velden typt naar style="color:blue; text-align: ..." in de wiki te zetten op de juiste plaats.

Wat er gebeurd als een ontwerper "hide" selecteert in de GUI is dat er helemaal geen Lens voor wordt gemaakt , dus dat er ook geen Form, template, categorie, properties voor komen, dus hij bestaat gewoon niet voor de fresnel2wiki generatie. (Hij bestaat alleen in de RDF ontologie). Is het niet correct om het zo te laten?

**Comment by AlexMekkering** [comment]
Wanneer in de GUI een lens hidden wordt gemaakt wordt die inderdaad expliciet uit de Fresnel RDF gehaald. Ik denk dat het inderdaad correct is om het zo te laten en dit issue te sluiten.

**Comment by LloydRutledge** [comment]
Zo is het goed, bedankt. Niet echt belangrijk, maar slaat de huidige plugin dan de hidden lenses up buiten Fresnel in het bestand, zo dat de hidden lenses als hidden lenses blijven de volgend keer dat het bestand ingelezen wordt? Of verdwijnen de hidden lenses na afloop van de sessie.  Maakt me niet zo veel uit maar ik ben benieuwd.

**Comment by AlexMekkering** [comment]
De hidden lenses worden niet opgeslagen in de doel(fresnel) ontologie. Bij het inlezen van de fresnel ontologie worden voor alle klassen van de bronontologie lenses gedefinieerd welke standaard hidden zijn en slechts voor degene die in het fresnel bestand staan wordt de status op shown gezet.
