### ISSUE TITLE
OWF TBL-pagina genereerd equivalent RDF export als de DPBedia ervoor

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#45]
Deze is nog een ondersteuning van ons kern stelling dat on implementatie moet hebben voor de Forms paper. De paper moet tonen dat ons systeem kan dezelfde RDF als export regelen dat DBPedia van de bijhorende Wikipedia-pagina uittrekt.

Joop, kan je regelen dat de TBL-pagina dat ons demo genereerd het equivalent is als die van DBPedia? SMW componenten die ervoor nodig zijn zijn (o.a.?) [[EquivalentURI::...]] en [[Imported from::...]]. [[EquivalentURI::...] was al in de PHP dus misschien al in onze OWF? Met [[Imported from::...]] heb ik zelf nog niets gedaan. Die twee zijn bovenan op https://svnext.ou.nl/INF_Studenten_ABI_team30/source/trunk/FresnelForms/design/OWFdev.xlsx .

Deze is nog een detail van #27 . Meer informatie op http://is.cs.ou.nl/SW_CRS/index.php5/Wikipedia_Tim_Berners-Lee_scenario .

De RDF code van onze demo zou je kunnen maken via http://abiteam30.lukylx.org:3080/mediawiki/index.php/Speciaal:RDFExporteren en het invoeren van "TimTest" (of de pagina dat on demo genereert?). De doel trek je uit van http://dbpedia.org/page/Tim_Berners-Lee. Maar die is heel veel! Dus op de CRS wiki heb ik een uittreksel geregeld van de RDF dat in onze export moet zijn. Ik moet nog wat toevoegen, maar die is minstens 80% klaar.

"Equivalent RDF" zou ook via reasoning komen. [[EquivalentURI::...]] regels een RDF export met een owl:sameAs waardoor een externe URI via reasoning "hetzelfde" wordt als de URI voor de pagina in de wiki export. Maar ik denk dat  [[Imported from::...]] een beter oplossing regelt om de altijd die extern URI direct bij RDF export te gebruiken, zonder sameAs tussenin.

**Comment by jheijning** [comment]
@LloydRutledge Door een pagina MediaWiki:smw_import_foaf te maken:
http://abiteam30.lukylx.org:3080/mediawiki/index.php/MediaWiki:Smw_import_foaf
en dan de property pagina een [[imported from::foaf:name]] tag te geven:
http://abiteam30.lukylx.org:3080/mediawiki/index.php/Property:Name
komt er in de RDF export <foaf:name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Sir Tim Berners-Lee</foaf:name>: 
http://abiteam30.lukylx.org:3080/mediawiki/index.php/Special:ExportRDF/Tim_Berners_Lee

Dus het zou voldoen om tijdens het opbouwen van de import XML ook pagina's MediaWiki:smw_import_*** op te bouwen met de nodige informatie. Dan heb je equivalentURI niet nodig.

Is dit een mogelijke oplossing?

**Comment by jheijning** [comment]
Nu doe ik dezelfde RDF export, maar dan via fresnel2wiki gegenereerde wiki en geeft mijn browser een xml fout: 	xmlns:xmlns.com/foaf/0.1/="http://xmlns.com/foaf/0.1/">
                -----------------------^
Geen idee.. Volgende week probeer ik verder.

**Comment by LloydRutledge** [comment]
Ja, dat is een veel betere oplossing. Dan wordt de URI direct in alle triples van de pagina. En hoeft je geen reasoner nodig om die af te leiden. Staat ook in de OWFdev.xlsx tabel. Zet die a.u.b. in Fresnel2wiki. En dan voor alle namespaces van de ontologie met hun prefixes en niet allen FOAF.

Je fout lijkt dat je de FOAF URI en niet prefix in die plek zit. Dus moet "xmlns.com/foaf/0.1/" "foaf" worden en dan krijg je xmlns:foaf="http://xmlns.com/foaf/0.1/". Toch? Het lijkt me dat fresnel2wiki gewoon de verkeerde variable gebruikt in de string generator. Zo ja dan moet het makkelijke te maken zijn.

Hieronder de betreffende deel van de feature tabel met de features waarover wij het nu hebben in rood. Klopt dat? En klopt het dat deze rode features geel kunnen worden nu al of binnenkort?

![naamloos](https://cloud.githubusercontent.com/assets/1098321/6264463/8b7fc24c-b824-11e4-8cde-571a8486cee7.png)

**Comment by LloydRutledge** [comment]
... eigenlijk toch als rood in SVN. Naast die cardinality van Teun. Rood is voor Forms paper milestone

**Comment by jheijning** [comment]
klopt, zie de zojuist gestuurde email 6:57pm feb 22 voor een update.

**Comment by LloydRutledge** [comment]
Bedankt. Ik heb de huidige RDF op pagina 15 in de submission draft gezet als plaatshouder en ons en idee te geven van de rol van de voorbeeld in de paper. Ik maak die opnieuw als de release komt met [[Imported From:]] en direct externe URI's in de RDF export. Ik maak die door de wiki export door  http://rdf-translator.appspot.com/ naar N3 te zetten en dat de minder belangrijke triples eruit knippen.

![knipsel](https://cloud.githubusercontent.com/assets/1098321/6320218/d2c0e558-bad8-11e4-93bf-ec08d9ef879a.JPG)

**Comment by jheijning** [comment]
Alex review alsjeblieft r392. unittest komt vanavond laat nog.

**Comment by AlexMekkering** [comment]
Code goed, output goed, dus review OK.
Ik heb nog een kleine refectoring en reformatting doorgevoerd in r400.

**Comment by jheijning** [comment]
Checked.

**Comment by LloydRutledge** [comment]
Nu in submission https://svnext.ou.nl/INF_Studenten_ABI_team30/Environment%20&%20Misc/SWCSlncsFForms.docx
