### ISSUE TITLE
TBL Fresnel lijkt op Wikipedia infobox op Fresnel browsers

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#46]
Onze paper moet kunnen beargumenteren dat de Fresnel dat ons scenario demo sessie maakt wat op de Wikipedia infobox lijkt als die op een willekeurige Fresnel browser toont met de RDF dat onze demo van de wiki exporteert. Dat we wat erover kan beargumenteren is een "Must".

 Dat we het werkelijk met een andere Fresnel browser tonen is een "Should". Tim uit ABI 28 heeft de Longwell Fresnel browser kunnen draaien. Maar na veel moeite, voornamelijk door de veroudert system requirements van Longwell. En dat was Tim niet mee eens met hoe Longwell de Fresnel toont! Het zou dus heel handig en mooi zijn als we ons exporteert Fresnel code kunnen verifiëren met een "authority/officiel" Fresnel browser van iemand anders. Maar misschien is dat niet mogelijk.

**Comment by TeunTheunissen** [comment]
Ha Lloyd, De enige fresnel browser die ik heb kunnen vinden is Lena (https://code.google.com/p/lena/)
De applicatie is een apache tomcat extensie. Wellicht kunnen ik iets installeren op Alex zijn testserver?
@Alex? Heb jij tomcat, welke rechten heb ik op jouw server?

**Comment by AlexMekkering** [comment]
Wanneer je inlogt met Putty met je gebruikersnaam en wachtwoord (ooit eens via de mail gekregen) heb je alle rechten. Wanneer je een beetje thuis bent in Ubuntu, kun je het dus zelf, anders wil ik er dit weekeinde ook wel even naar kijken.

**Comment by TeunTheunissen** [comment]
klopt ik heb hier nog wat aan accounts liggen, ik ga het proberen met putty en laat je weten of het lukt.

**Comment by TeunTheunissen** [comment]
@Alex, putty werkt prima, kan ook in je server maar de unix command prompt.. , dat is te wild voor mij.
Ik heb thuis nog wel eens met een desktop ubuntu gespeeld, dat was nog wel te doen.
Dus als je tijd hebt dit weekend, graag.

**Comment by LloydRutledge** [comment]
Zal nuttig zijn als we z'n bevestigende externe Fresnel browser hebben. Tim Zwanenberg van de vorige ABI heeft wat met Longwell gedaan (zie boven). Misschien heeft ie tips.

**Comment by TeunTheunissen** [comment]
Het probleem met Longwell is dat dit project opgeheven is, de webpagina's bestaan niet meer.
Het Lena project is het enige project dat nog te vinden is op het web.

**Comment by AlexMekkering** [comment]
Lena 2.0.5a beschikbaar op http://abiteam30.lukylx.org:3081/lena-2.0.5a/

**Comment by LloydRutledge** [comment]
Bedankt voor de install. Maar ik kan niks zien. Moet ik iets anders doen?

![knipsel](https://cloud.githubusercontent.com/assets/1098321/5967136/75cb50da-a80a-11e4-98cc-1f2e66dcc6f1.jpg)

**Comment by AlexMekkering** [comment]
Sorry, 't is nog slechts geïnstalleerd. We moeten nog even uitzoeken hoe we het kunnen gebruiken en vullen met gegevens. Ik begreep van Teun dat ie daar morgen mee wilde beginnen.

**Comment by LloydRutledge** [comment]
Oké, bedankt, ik zal dan gewoon geduld hebben. Kunnen we de kern doel stellen als het kunnen maken van een weergave van de TBL voorbeeld? Dan zetten we die in de Forms paper submission.

**Comment by TeunTheunissen** [comment]
Lena laat een voorbeeld foaf ontology zien met behulp van lensen. Ik zal later de berners-lee ontology installeren voor onze test.

**Comment by TeunTheunissen** [comment]
Ik heb een uittreksel gemaakt van de dbpedia ontology (dbpedia_2014.owl.bz2) van de Tim Berners-Lee gegevens. Dit uitreksel staat in subversion in de map: 
    "Environment & Misc\Ontologies\DBPedia_TBL_Extract"
Dit uitreksel heb ik ook bij Lena geinstalleerd, samen met de default Fresnel die onze plugin genereerd.
Wat opvalt is dat onze Fresnel definitie alle properties van een classe laat zien in de bijbehorende lens die gedefinieerd zijn in de ontology zelf maar niet de properties die gedefinieerd zijn in een ontology waar naar verwezen wordt. zie "foaf:depiction".
@LloydRutledge Graag commentaar.
@AlexMekkering review fresnel generatie.
@jheijning  review fresnel opmaak, kunnen we de css opmaak terug zien in Lena?

**Comment by LloydRutledge** [comment]
@TeunTheunissen enkele terugkoppelingen.

Hoe kan ik de Lena weergave zien? Ergens al op http://abiteam30.lukylx.org:3081/lena-2.0.5a/ ? Of kan ik daar zelf het bestand invoeren? Het Fresnel weergave van deze RDF is een belangrijk aspect van de RDF.

Waar me meerdere labels en comments heb beperkt dit tot alleen de ene in het Engels. Of filters Fresnel al op taal? Anders zet Lena meerdere labels op, of kiest misschien een niet-Engelse label.

Veel van dit bestand heeft uittreksels van de ontologie. Is dat nodig? Kunnen we een bestand in Lena voeren met alleen triples direct over TBL en een verwijzing naar de ontologie. Die ontologie kan de originele hele zijn of ons uittreksel van die ontologie maar dan met alleen ontologisch triples en niks met individuals zoals TBL?

**Comment by TeunTheunissen** [comment]
Lena voorzien van de locale ontology 'TheFirm' met een paar kleine aanpassingen.
De lens 'Person lens' laat zien wat er nu mogelijk is met Lena. Helaas wordt de css styling niet ondersteund. Ik heb een email gestuurd naar een van de programmeurs van Lena met de vraag wat er nog mogelijk is.
De configuratie,gebruik en ontology aanpassingen staan gedocumenteerd op onze wiki, zie pagina: http://is.cs.ou.nl/ABI30/index.php5/Lena_configuratie
@LloydRutledge  De hyperlink geeft toegang tot de Lena browser. Deze browser laat dan een lokale ontology zien (TheFirm) eventueel via de lensen zoals ze lokaal gedefinieerd. Je kan dus niet zelf bestanden invoeren. Wel kun je via ftp bestanden (owl,fresenl.n3) in de daarvoor aangegeven mappen zetten. Die worden dan getoond door Lena. (Zie de wiki voor alle details)

De status van dit issue is dat ik wacht op antwoord van de Lena programmeur.

**Comment by AlexMekkering** [comment]
Ik vind dat we niet meer kunnen doen om dit issue aan te tonen, dus vooralsnog sluiten maar.
