### ISSUE TITLE
Exporteren van images naar wiki heeft nog niet het gewenste resultaat

### ISSUE THREAD

**Issue by AlexMekkering** [ABI-Team-30/Fresnel-Forms#50]
Bij het exporteren van images wordt in SMW nog niet het plaatje weergegeven.

Dit issue is voortgekomen uit werkzaamheden aan #5.

**Comment by jheijning** [comment]
$wgAllowImageTag had ik tot nu toe blijkbaar nog niet geprobeerd, want deze werkt wel! Dus issue opgelost. <img style="width:250px; ...;" src="url">  Dus de CSS kan gewoon rechtstreeks geplakt worden, geen parsing nodig! Teun please review.

**Comment by LloydRutledge** [comment]
Leuk, zie ik! Kunnen jullie deze en dergelijk instructies in een download/install document zetten? Zoals op http://is.cs.ou.nl/ABI30/index.php5/Bouwen_Fresnel_Forms of een pagina erbij? Wij hebben hier en volgens mij elders wat instructies over wat er nodig is in de LocalSettings.php.

**Comment by jheijning** [comment]
Voorlopige install pagina: http://is.cs.ou.nl/ABI30/index.php5/Installation_Fresnel_Forms_for_End_Users

**Comment by TeunTheunissen** [comment]
Review is OK, plaatje wordt getoond in de wiki met de css styling die toegevoegd wordt aan het fresnel model is het formaat aan te passen.
