### ISSUE TITLE
Geen nieuw resultaat bij meerdere keren "save wiki".

### ISSUE THREAD

**Issue by jheijning** [ABI-Team-30/Fresnel-Forms#52]
Ik heb het nu een paar keer geprobeerd: Als je Protégé opent, je maakt wat format aanpassingen, je exporteert de wiki dan heb je een xml file. Als je daarna wat andere format aanpassingen maakt en je weer wiki exporteert dan worden de nieuwe aanpassingen niet meegenomen. Wie weet dat hetzelfde ook is gebeurd toen Teun de delimiter testte.

**Comment by jheijning** [comment]
Ik denk dat ik al weet wat er gebeurd: de arrayList met pagina's in fresnel2wiki zit nog vol van de eerste export en de nieuwe worden er gewoon achter geplakt. dus oplossing is arraylist leegmaken na een export lijkt me..

**Comment by jheijning** [comment]
Zojuist functioneel getest en probleem lijkt verholpen te zijn. Wil jij ff reviewen Alex (één regel aan code toegevoegd)?

**Comment by AlexMekkering** [comment]
Ziet er inderdaad goed uit en functioneel werkt het ook nog! :+1: 
Wat mij betreft kunnen we deze dus sluiten.
