### ISSUE TITLE
Definitief versie Protégé voor ontwikkeling en documentatie (o.a.?)

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#53]
We hebben over zowel beta-15 als beta-16 in verschillende documentatie. En alleen 16 werkt met de volle DBpedia ontologie. Beta-15 kwam eerder voor in http://is.cs.ou.nl/ABI30/index.php5/Installation_Fresnel_Forms_for_End_Users. Beta-16 is de versie die nu komt van de instructies in http://is.cs.ou.nl/ABI30/index.php5/Bouwen_Prot%C3%A9g%C3%A9_5. Maar dan noemen die instructies geen specifiek versie; die heeft alleen in link maar de Protégé Github, waar gewoon de laatste versie op die moment altijd zit.

Is er een project manier om officieel ontwikkelingsversies van extern software te bepalen en melden en documenten en verzekeren dat die consequent gebruikt wordt? Voor ons is dit meeste belangrijk voor Protégé. Maar zou ook voor Semantic Forms, andere extentions, SMW, MW en eventueel zelfs PHP belangrijk kunnen zijn. Weten jullie of er een bekende vak gebruikte oplossing hiervoor is?

Ik heb ons wiki wat consequenter gemaakt om een verwijzing naar de Protege pagina te zetten van de Fresnel Forms. En de build nummer wel in de Protégé pagina te noemen, en dan alleen daar.

**Comment by AlexMekkering** [comment]
De directe afhankelijkheden (pakketten welke nodig zijn om te kunnen compileren) van het project staan expliciet in het pom.xml bestand welke maven gebruikt om de onderliggende afhankelijkheden op te lossen. Eigenlijk gebeurt het meeste dus automagisch door maven, de dependencies zoals ze nu zijn gedefinieerd zijn:
```xml
	<dependencies>
		<dependency>
			<groupId>edu.stanford.protege</groupId>
			<artifactId>org.protege.editor.core.application</artifactId>
			<version>5.0.0-beta-16-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>edu.stanford.protege</groupId>
			<artifactId>org.protege.editor.owl</artifactId>
			<version>5.0.0-beta-16-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
            <scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.jena</groupId>
			<artifactId>apache-jena-libs</artifactId>
			<type>pom</type>
			<version>2.12.1</version>
		</dependency>
	</dependencies>
```

Voor versienummers van MediaWiki, SMW, Semantic Forms, PHP, MySQL etc. kan dit opgevraagd worden aan bijv. http://abiteam30.lukylx.org:3080/mediawiki/index.php/Speciaal:Softwareversie van onze installatie waarop we testen.
Grofweg hebben we de standaard packages gebruikt welke op Ubuntu Desktop 14.04.1 gelden d.d.2015-02-11. Op dit moment hebben we het met de volgende versies van afzonderlijke paketten getest:

Product | Version
---------- | ----------
[MediaWiki](https://www.mediawiki.org/) | 1.19.14+dfsg-1
[PHP](http://www.php.net/) | 5.5.9-1ubuntu4.5 (apache2handler)
[MySQL](http://www.mysql.com/) | 5.5.41-0ubuntu0.14.04.1
[Semantic Forms](https://www.mediawiki.org/wiki/Extension:Semantic_Forms) | 2.8
[Semantic MediaWiki](https://semantic-mediawiki.org/) | 2.0

Ik denk dat de mooiste plaats om dit te registreren, het README.md bestand op GitHub is. Deze bestaat nog niet, maar kan natuurlijk eenvoudig aangemaakt worden. Het heeft dezelfde markup mogelijkheden als deze issuetracker en het is voor de gebruiker wellicht de eerste kennismaking aangezien deze standaard getoond wordt indien aanwezig.

**Comment by AlexMekkering** [comment]
Ik heb de mvn afhankelijkheden voor FresnelForms nu ook verlegd naar Protege 5.0.0.beta15 aangezien deze in mvn standaard aanwezig is in de mvn repository (zie http://mvnrepository.com/artifact/edu.stanford.protege/org.protege.editor.owl/5.0.0-beta-15).
Dit heeft als voordeel dat Protege nu niet meer vanuit git gebouwd hoeft te worden, maar gewoon gedownload kan worden vanaf de stanford site (http://protege.stanford.edu/products.php#desktop-protege) en FresnelForms meer out-of-the-box werkt wanneer het uit svn gehaald wordt.
De afhankelijkheden zijn nu:
```xml
<dependencies>
	<dependency>
		<groupId>edu.stanford.protege</groupId>
		<artifactId>org.protege.editor.core.application</artifactId>
		<version>5.0.0-beta-15</version>
		<scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>edu.stanford.protege</groupId>
		<artifactId>org.protege.editor.owl</artifactId>
		<version>5.0.0-beta-15</version>
		<scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>4.11</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.apache.jena</groupId>
		<artifactId>apache-jena-libs</artifactId>
		<type>pom</type>
		<version>2.12.1</version>
	</dependency>
</dependencies>
```

Daarbij heb ik de unit tests geldig gemaakt voor op case-sensitive bestandssystemen waardoor het bouwen ook onder bijv. linux goed werkt.

Al met al is de compatibiliteit met bestands- en besturingssystemen dus vergroot en is er minder nodig om FresnelForms te kunnen bouwen vanuit de broncode, waardoor het door een grotere groep eindgebruikers gebruikt kan worden.

**Comment by AlexMekkering** [comment]
http://is.cs.ou.nl/ABI30/index.php5/Installation_Fresnel_Forms_for_End_Users is aangepast met vernieuwde (eenvoudigere) instructies voor eindgebruikers, inclusief compatibility table.

**Comment by AlexMekkering** [comment]
Lijkt me opgelost met de compatibility table op http://is.cs.ou.nl/ABI30/index.php5/Installation_Fresnel_Forms_for_End_Users.
