### ISSUE TITLE
Default CSS laten zien in gui edit CSS box.

### ISSUE THREAD

**Issue by jheijning** [ABI-Team-30/Fresnel-Forms#56]
Hard-coded in fresnel2wiki is nu default CSS voor de resource/property/label/value. Zou mooi zijn om deze te laten zien in de gui edit CSS box ter informatie voor de gebruiker. Eventueel ook textarea i.p.v. textfield.

**Comment by jheijning** [comment]
Aan de gui-guru

**Comment by jheijning** [comment]
Kijken hoe default CSS beschikbaar maken.

**Comment by LloydRutledge** [comment]
Joop: install instructies met CSS to kopieren en waar
Alex    
Default CSS naar Joop
Default CSS niet meer in Fresnel

**Comment by AlexMekkering** [comment]
Implementatie aangepast in r361.

De default CSS is nu beschikbaar in stylesheet http://abiteam30.lukylx.org:3080/mediawiki/index.php/MediaWiki:OWF.css.
@LloydRutledge, je kunt de default CSS die we gebruiken daar dus raadplegen. Ik heb de preliminary release https://github.com/ABI-Team-30/Fresnel-Forms/releases/tag/1.0.10-SNAPSHOT_stylesheet gemaakt waarmee je evt. zelf iets zou kunnen proberen, mocht je dat willen.

Er is ieder geval weer een verse versie van de Infobox klaargezet op http://abiteam30.lukylx.org:3080/mediawiki/index.php/Tim_Berners_Lee. Deze is gegenereerd met https://github.com/ABI-Team-30/Fresnel-Forms/blob/master/Ontologies/tbl_stylesheet.fresnel en onze meest recente dbpedia extraction en maakt dus gebruik van de OWF.css stylesheet in MediaWiki. Ik heb geprobeerd om het zo goed mogelijk op die van http://en.wikipedia.org/wiki/Tim_Berners-Lee te laten lijken.

@jheijning, wil jij het reviewen?

**Comment by jheijning** [comment]
Review OK.

Wat betreft het gebruik van de OWF.css stylesheet: Dan zou één van de stappen in http://is.cs.ou.nl/ABI30/index.php5/Installation_Fresnel_Forms_for_End_Users moeten zijn het installereven van OWF, niet waar? Kun je de css niet gewoon in mediawiki:commons.css plakken?

**Comment by jheijning** [comment]
Dat laatste blijkt te werken voor zover ik kan zien. Dus stap 3 toegevoegd aan http://is.cs.ou.nl/ABI30/index.php5/Installation_Fresnel_Forms_for_End_Users . Voel je vrij om te undo the changes in commons.css .

**Comment by AlexMekkering** [comment]
De OWF.css bestond al (waarschijnlijk aangemaakt bij het installeren van OWF.php?) en daarom heb ik 'm op die manier gebruikt. Common.css werkt natuurlijk ook gewoon, dus prima.

Is het een plan om de default CSS, zoals nu op onze testserver aanwezig is, ergens in onze svn repository te plaatsen en daarnaar te verwijzen? Een garantie dat onze testserver te allen tijde beschikbaar is, is er namelijk niet.

**Comment by jheijning** [comment]
Of misschien nog beter gewoon op dezelfde wiki? dat heb ik nu gedaan http://is.cs.ou.nl/ABI30/index.php5/Installation_Fresnel_Forms_for_End_Users#Installation & http://is.cs.ou.nl/ABI30/index.php5/Default_CSS_Fresnel_Forms  Voel je weer vrij om te wijzigen natuurlijk.

**Comment by LloydRutledge** [comment]
Ik zet alles binnenkort op de openbare wiki http://is.cs.ou.nl/OWF/ . Voor mij heeft deze een einddatum net na de submission zodat de reviewers die kan benutten. Misschien begin ik die toch deze week.

**Comment by AlexMekkering** [comment]
Issue lijkt me opgelost met beschikbaarheid via http://is.cs.ou.nl/ABI30/index.php5/Default_CSS_Fresnel_Forms.
