### ISSUE TITLE
Css van het label wordt niet getoond.

### ISSUE THREAD

**Issue by TeunTheunissen** [ABI-Team-30/Fresnel-Forms#59]
De css van een label wordt overriden door de css style van de hyperlink. klopt want het is een hyperlink. Maar hierdoor kan bv de font color niet op zwart gezet worden.

**Comment by TeunTheunissen** [comment]
opgelost in revisie 398, 1 regel code aangepast zie class fresnel2wiki regel 288.
@jheijning please review.

**Comment by jheijning** [comment]
Het probleem is adequaat opgelost, maar het introduceert, mijns inziens, een ander probleem, namelijk dat je zo ook de semantische verwijzing kwijt raakt.

**Comment by AlexMekkering** [comment]
@LloydRutledge:
Zoals het label in dit issue is geïmplementeerd worden labels van properties gewoon tekst op een infobox (Eigenlijk zoals een standaard label eruit moet zien). Vóór deze wijziging echter, was een label een semantische verwijzing naar de property waar het bijhoort. Hierdoor werd de CSS van het label door SMW overschreven met de standaard CSS van een hyperlink.

Ben je het ermee eens dat labels nu gewoon tekst zijn, of wil je het toch liever verwijzingen laten blijven naar de bijbehorende Property page? (De eerste optie geeft dus meer overeenkomsten met de wikipedia infoboxes, de tweede optie resulteert in meer semantische waarde binnen infoboxes, maar lijkt minder op de standaard infoboxes.)

**Comment by LloydRutledge** [comment]
Met "semantisch verwijzing" bedoel je een navigatie hyperlink naar de property-pagina? Zo ja dan prima, die is niet nodig. De SF Form-generator maakt geen property links. WP heeft ook geen dergelijk linkerkolom links. Ik gebruik die nauwelijks op mijn eigen semantic wiki. Die had ik wel in de PHP OWF. Dus Joop had waarschijnlijk die daar tegen gekomen.

... of ... bedoelen jullie iets anders met "semantisch verwijzing"? Er moet wel een [[Property::Value]] in SMW-code komen.

**Comment by AlexMekkering** [comment]
De Property pagina's worden natuurlijk wel gewoon gegenereerd. Het enige is dat daar vanuit de labels niet meer naar verwezen wordt. Met de [[Property::Value]] denk ik dat je doelt op de link vanuit de waarde, welke ook gewoon aanwezig is.
Zo ja, dan kunnen we deze ook sluiten denk ik.
