### ISSUE TITLE
De website toont geen external URL, terwijl dat wel in de fresnel gedefinieerd is.

### ISSUE THREAD

**Issue by TeunTheunissen** [ABI-Team-30/Fresnel-Forms#60]
de URL wordt getoond als wikipagina en niet als externe url.

**Comment by TeunTheunissen** [comment]
opgelost in revisie 399. zie o.a. regel 132 in de fresnel2wiki classe 
@jheijning please review

**Comment by jheijning** [comment]
Teun, ik zie dat je de arrayMap functie |xxx|[xxx xxx] meegeeft ipv |xxx|[[propertyName::xxx]] . Wat is daar de functie van?

Ik heb in http://abiteam30.lukylx.org:3080/mediawiki/index.php?title=Template:Informbox_Person&action=edit als test er gewoon {{#arraymap:{{{homepage|}}}|,|xxx|[[homepage::xxx]]}} van gemaakt en het lijkt geen probleem te zijn.

**Comment by TeunTheunissen** [comment]
De functie van [xxx xxx] is dat de url getoond wordt met als label de url zelf. Met [homepage::xxx] krijg ik de url met de label homepage ervoor en dat is volgens de wikipedia pagina niet de bedoeling.

**Comment by AlexMekkering** [comment]
Ik denk ook dat de oplossing van Teun voor externe URLs correct is voor infoboxes. Er is voor externe URLs volgens mij ook geen semantische waarde anders dan het feit dat het om een (externe) verwijzing gaat.

Daarom denk ik dat het goed is dat we deze sluiten.
