### ISSUE TITLE
Change type laat niet het ingestelde type zien na het laden van een fresnel bestand.

### ISSUE THREAD

**Issue by TeunTheunissen** [ABI-Team-30/Fresnel-Forms#62]
Na het laden van een fresnel bestand wordt het type niet getoond het staat op URI.

**Comment by TeunTheunissen** [comment]
Bij het laden van het bestand werd de fresnel.value property niet meegenomen in de propertybinding settings. Aangepast in methode 'JenaFresnelModel.formatPropertyBinding'.
@AlexMekkering please review.

**Comment by AlexMekkering** [comment]
Review commentaar:

Allereerst: goede bevinding :+1: 

Inhoudelijk:
Bij het gebruik van de String.equals methode kun je beter de statische string als uitgangspunt gebruiken omdat die gegarandeerd bestaat, dus bijv:
 - `FRESNEL.IMAGE.equals(object.asResource())` ipv `object.asResource().equals(FRESNEL.IMAGE)`
In dit geval krijg je namelijk, wanneer het object niet als Resource kan worden benaderd, ófwel een exception van asResource() ófwel een null-pointer exception bij toepassen van .equals() (wanneer null terug wordt gegeven).

**Comment by TeunTheunissen** [comment]
Goede opmerking, het is gebeurd. ik sluit dit issue
