### ISSUE TITLE
Geen categorieen voor autocompleteFromClass

### ISSUE THREAD

**Issue by TeunTheunissen** [ABI-Team-30/Fresnel-Forms#64]
Er worden alleen categorieen aangemaakt voor lenzen die zichtbaar zijn. AutocompleteFromClass kan echter verwijzen naar die classen/lenzen. In de wiki kan er dan geen categorie voor bestaan.

**Comment by AlexMekkering** [comment]
Ik heb een meer compleet fresnel bestand gemaakt waarin alle benodigde lenzen aanwezig zijn in r413.
Ook heb ik de wiki xml output erbij gezet als referentie. Deze kan gebruikt worden om gegenereerde output eenvoudig te vergelijken tegen deze basis (met bijv. TortoiseSVN): het enige wat je hoeft te doen is dit bestand overschrijven en met TortoiseSVN->diff de verschillen te bekijken. Kan dus ook gebruikt worden als regressietest :wink:

Zie https://svnext.ou.nl/INF_Studenten_ABI_team30/Environment%20&%20Misc/Ontologies/DBPedia_TBL_Extract/TBL_extract_person.n3 voor de fresnel output en https://svnext.ou.nl/INF_Studenten_ABI_team30/Environment%20&%20Misc/Ontologies/DBPedia_TBL_Extract/TBL_extract_person.xml voor de wiki output

**Comment by AlexMekkering** [comment]
Dit lijkt me een algemeen probleem en is op te lossen door alle benodigde lenzen mee te nemen in de conversie naar SMW.
Ik stel voor om dit issue niet als bug te zien maar als notitie bij het exporteren naar SMW.
