### ISSUE TITLE
input type=datetime enz

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#65]
Kan Fresnel2wiki input types genereren op de forms zoals date? Dan komen de best gepast input tools ervoor. Leidende voorbeeld is de TBL birthDate, met hierbij de weergave die in de submission gebruikt wordt. Met |input type=date in de Form zal er een datumgericht input veld in de form komen. Kunnen we dat regelen? En eventueel voor andere Forms input types die goed met XSD datatypes gaan?

Een handige tabel is op http://www.mediawiki.org/wiki/Extension:Semantic_Forms/Defining_forms#Allowed_input_types_for_data_types . Van die tabel moet ik me afvragen waarom de [[Has type::Date]] die all op Property:BirthDate niet de default input type Date veroorzaakt. Het hier opgeschreven gewenst gedrag moet eigenlijk al gebeuren.

![tblform](https://cloud.githubusercontent.com/assets/1098321/6425951/e791bae0-bf40-11e4-87b0-5a8f1254913a.jpg)

**Comment by LloydRutledge** [comment]
Moet zo eruit zien:

![tblform](https://cloud.githubusercontent.com/assets/1098321/6426170/0ae2e850-bf4d-11e4-8819-1640f87ba4dd.jpg)

**Comment by LloydRutledge** [comment]
Handig als die weergave in de submission gezet kan worden, ook met discussie over hoe de input types voor de formulieren de gebruiker helpen. En dat je van de ontology default bepaald worden.

**Comment by LloydRutledge** [comment]
Misschien kan Teun dit eerst in de Fresnel-OWF ontologie en dan in de default generator. And daarna kan Joop (ja, na de vakantie) die in Fresnel2wiki zetten. Als jullie deze (laatste?) nieuwe (en late) feature voor de paper en project willen aanpakken?

**Comment by LloydRutledge** [comment]
Assignee nu naar me. Ik kan wel een wiki opstellen waarmee de default input type voor date goed werk. Dus moet verandering in default Fresnel generator en (voorlopig) de Fresnel-OWF ontologie niet nodig zijn. Maar dan werkt het nog niet in de wiki import van Fresnel2wiki. Ik kan het verschil niet goed zien maar ik blijf zoeken. Dan misschien zie ik hoe Fresnel2wiki aangepast moet worden.

**Comment by AlexMekkering** [comment]
Ik was net bezig gegaan met het expliciet toevoegen van input type=date voor Date properties. Zie http://abiteam30.lukylx.org:3080/mediawiki/index.php/Special:FormEdit/Person/Tim_Berners_Lee welke gegenereerd is vanuit fresnel2wiki (nog niet gecommit).

Het kan zijn dat we tegelijktijdig aan dezelfde pagina (Form:Person) hebben gezeten, waardoor je beeld over de Form niet eenduidig was en verwarrend.

Zal ik de wijzigingen toch comitten? Het voegt immers slechts een expliciete input type toe voor Properties met het datatype xsd:date.

**Comment by LloydRutledge** [comment]
Alex, bedankt voor het expliciete toevoegen! Het maakt de voorbeeld goed voor de paper. Het moet onnodig zijn, maar het lost op wat waarschijnlijk een bug van SF is, en dat kunnen we niet snel fixen.

Maar het lijkt me nu dat SF hiermee goed werkt als card<=1. Het lijkt dat default input types niet herkend worden met |list op de Form en/of arraymaps voor de waarde voor die property. Als ik die met de hand aanpas na de import van fresnel2wiki dan lijkt het te werken. Denk ik - ik ben nog aan het testen. En dan als we een card<=1 als eigen onto uitbreiding op DBP en/of als Fresnel-OWF component dan moet het werken. Minstens voldoende voor de TBL voorbeeld.

Het is vast inhoudelijke verrijkend voor de submission om te spreken over je we het aantal birthDates per Person Form tot één (of nul) beperken, want dan is dat ook nuttig voor wikipedia. Dus ideëler zonder expliciet type (die onnodig moet zijn) maar via card<=1 op de onto of OWF stylesheet.

Het is toch raar dat SF geen default input type gebruikt met lists. Maar die is niet nodig voor de TBL voorbeeld. En het lijkt meer een  bug in SF dan iets waarvoor we expres een onnodige override moet exporteren.

Ik ben hiermee nog aan het onderzoeken. Of het echt zo is dat alleen list en arraymap weg het fixt. Dan zo het moeten werken met card<=1 via de release van vanavond.

**Comment by AlexMekkering** [comment]
OK, wijziging voor expliciete `input type=date` toegevoegd in r415.

@TeunTheunissen, please review.

**Comment by LloydRutledge** [comment]
Laten we het zo houden met de expliciete toevoeging. Ik krijg de default voor niet-lists/arraymaps op SF voor een geminimaliseerde voorbeeld maar niet bij aanpassingen op de TBL voorbeeld. Als ik ooit SF goed draaiend krijgen dan kan ik het zelf aanpassing - dat lijkt na jullie tijd te worden.

**Comment by LloydRutledge** [comment]
Date input op Form voor TBL voorbeeld nu in submissions draft als figuur

![knipsel](https://cloud.githubusercontent.com/assets/1098321/6431659/201c6526-c037-11e4-9e0c-0acf8a044919.JPG)

**Comment by TeunTheunissen** [comment]
review OK,
