### ISSUE TITLE
2ary namespace voor alles op wiki en Fresnel

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#66]
Moet nog voor property pagina's. Is al in veel fresnel. Bijvoorbeeld uit FOAF moet Property:accountName worden Property:foaf-accountName.

**Comment by AlexMekkering** [comment]
Ingevoerd in r453.

De gehele wijziging heeft nogal wat impact die ik nu even niet kan overzien.
@jheijning , kun jij dit met jou berg aan kennis en ervaring over de wiki syntax aan een review onderwerpen? Ik ben met name geïnteresseerd of de smwImport pages zo goed zijn of dat daar de namespaces ook dieper geïntegreerd moeten worden.

Ook is hiermee de gehele fresnel2wiki verwerking een stuk schaalbaarder geworden omdat er minder objecten/lijsten & strings bijgehouden worden en dus minder geheugen gebruikt wordt.

**Comment by jheijning** [comment]
Ziet er weer een stuk professioneler uit :-)

RDF export ziet er nog steeds zo uit zoals het moet (voor zover mijn kennis rijkt): 
![rdfexport voorbeeld](https://cloud.githubusercontent.com/assets/9306134/6618509/b40d7178-c8c3-11e4-8188-4d8badeba03f.PNG)

De pagenames hebben nu de prefix met een "-", wat de requirement was die we wilden toevoegen:
![import voorbeeld](https://cloud.githubusercontent.com/assets/9306134/6618654/a8caf2d0-c8c4-11e4-9195-6bf9a4f4c569.PNG)

infobox laat nog steeds goede labels zien:
![page](https://cloud.githubusercontent.com/assets/9306134/6618660/b5b55756-c8c4-11e4-8d64-4355ca9ddba8.PNG)

Alleen de form rijen hebben nu labels die niet helemaal zijn zoals je wilt lijkt me:
![form voorbeeld](https://cloud.githubusercontent.com/assets/9306134/6618668/c320eeb4-c8c4-11e4-9a8e-6d3b18da22d2.PNG)
Ik stel voor om een extra argument prop.getLocalName() aan formRow() te geven voor de form label om dit op te lossen. Simpele wijziging die ik zo meteen zal submitten, review jij hem even Alex?

**Comment by AlexMekkering** [comment]
Review goedgekeurd, samen met alle strubbelingen rond #68 en #69
