### ISSUE TITLE
Default Frensel knop eerste/linkste

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#67]
Kunnen we de Fresnel knop verplaatsen zodat het eerste is, en dus helemaal aan de linkerkant? Dan hebben de vier knoppen min of meer de zelfde volgorde als wat de gebruiker doet. Dus

1) Default Fresnel: lege scherm krijg begin punt die dan ge-edit wordt
2) Save Fresnel: eens ge-edit wordt het opgeslagen
3) Load Fresnel: eens opgeslagen wilt je het terug hebben
4) Save Wiki: de eindresultaat als de Fresnel af is

**Comment by AlexMekkering** [comment]
solved in r492

@jheijning, please review

**Comment by jheijning** [comment]
reviewed, alles goed. wat mij betreft kan die sluiten..
