### ISSUE TITLE
OWF PHP voor Fresnel-naar-wikicode porten

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#7]
De PHP voor de OWF extension op http://is.cs.ou.nl/OWF/index.php5/OWL_Wiki_Forms_v0.2_installation bevat code voor het SPARQL queryen voor Fresnel code om wikicode ervan te maken. Ik wil deze functionaliteit naar de Protégé plugin verplaatsen zodat de OWF extension overbodig wordt. En dat daarna jullie de functionaliteit uitbreiden. Dat is de kern van dit project. Dus wordt het porten van deze code een duidelijk eerste stap. Dus een "Must"

Het lijkt me makkelijker om de PHP met de SPARQL query's in Java te vertallen. Het kan natuurlijk opnieuw geschreven worden als de zelfde functionaliteit eruit komt. De oude extension kan met gegeven ontologieën gedraaide worden om test data te maken.

Ik tag deze als "blocking" en "critical" omdat meer van de kern functionaliteit er boven op gebouwd wordt, en dus moet deze eerst gebeuren.

**Comment by jheijning** [comment]
Gekeken, resultaat: Succes! Moet de issue nu gesloten worden, of later?

**Comment by AlexMekkering** [comment]
Super! Ik zou zeggen: Closed!
Het invullen van de Ranges valt wat mij betreft onder #29 en voor het behandelen van de formatted properties heb ik #31 aangemaakt.
