### ISSUE TITLE
"Could not load view plugin" foutbericht

### ISSUE THREAD

**Issue by LloydRutledge** [ABI-Team-30/Fresnel-Forms#71]
Meer informatie in de e-mail van een OU Masters studenten dat ik naar jullie doorgestuurd heb. Hij krijgt het "Could not load view plugin" foutbericht als hij met Protégé beta 17 ons plugin voor FOAF probeert te gebruiken. Ook andere ontologieën. Must en critical omdat we moeten controleren dat het geen probleem met beta 17 is.

**Comment by AlexMekkering** [comment]
FOAF werkt bij mij wel met Protégé beta 17 / Fresnel Forms 1.0.12, dus er lijkt me zo op 't eerste gezicht niet structureel iets mis, zie:
![image](https://cloud.githubusercontent.com/assets/9436555/6785196/7f36ebae-d184-11e4-90bc-8bf1e4dc2205.png)

Ik heb dit getest met een verse Protégé, dus zonder extra plugins. Ik heb het met foaf van vandaag en die van 2014-01-14 geprobeerd, beide met succes. Misschien is het iets wat specifiek is voor Maarten z'n setup? Hij zou ook nog het Protégé logging level aan kunnen passen in het bestand log4j.xml om te kijken met welke meldingen Protégé zelf nog komt.

**Comment by AlexMekkering** [comment]
Volgens de laatste berichten van Maarten werkt het nu bij hem. Er is echter niet bekend waardoor dit issue veroorzaakt kan zijn of wat de acties zijn geweest om het probleem op te lossen. Voor nu sluit ik hem daarom...
