### ISSUE TITLE
Verwijderen van eerder toegevoegde CSS wordt niet goed verwerkt in de Fresnel output

### ISSUE THREAD

**Issue by AlexMekkering** [ABI-Team-30/Fresnel-Forms#74]
Wanneer CSS stijlinformatie is opgeslagen en later weer wordt verwijderd, dan blijft deze aanwezig in zowel de Fresnel output als de MediaWiki XML output.

Een workaround is om de CSS nadien uit het fresnel bestand te halen.

**Comment by AlexMekkering** [comment]
Opgelost in r557. @TeunTheunissen, kun jij dit nog even reviewen?

Omdat er bij geen vuilling van de CSS geen propertyreplacement plaatsvond, werden de oude waarden ook niet verwijderd.

Ik heb het iets generieker aangepakt omdat dit probleem ook bij andere formatting properties kan optreden (dit trad namelijk ook op bij het property type (IMAGE of EXTERNALLINK)).
Ik heb daartoe de  JenaUtils.replaceProperty methode uitgebreid met de functionaliteit dat ook meerdere objecten als replacement kunnen worden aangeboden en wanneer een aangeboden object null is, of de lijst van objecten leeg is, de bestaande properties verwijderd worden.

**Comment by AlexMekkering** [comment]
@TeunTheunissen, wil jij hier nog iets over roepen en sluiten indien OK bevonden?

**Comment by TeunTheunissen** [comment]
OK, deze kan gesloten worden.
