### ISSUE TITLE
autocompleteFromClass verwijst naar verkeerde of niet bestaande Category

### ISSUE THREAD

**Issue by AlexMekkering** [ABI-Team-30/Fresnel-Forms#75]
Wanneer autocompletion voor een property aan staat, wordt verwezen naar een verkeerde of niet bestaande Category, waardoor autocompletion in zijn geheel niet of niet goed werkt.

**Comment by AlexMekkering** [comment]
Opgelost in r558. @jheijning, kun jij deze nog even reviewen?

Het probleem was dat de Articles voor lenzen (Category, Form & Template) de localname kregen van de Lens (zonder het Lens achtervoegsel), dus zonder namespace. De autocompletion classes (ranges van properties) waren echter op basis van de volledig URI van de range gedefinieerd, dus fully-qualified (zie #66).

Voor de oplossing heb ik de namen van de verschillende Articles (eigenlijk de basis boxName) gelijk gemaakt aan de (encoded) URI van de classLensDomain van de Lens. Eigenlijk had dit dus al voor #66 moeten gebeuren :blush:.

**Comment by jheijning** [comment]
Prima! Wellicht voor een volgend ABI project: Ook een routine standaard functionele test die dezelfde features test na elke ingrijpende wijziging zoals #66 . Unittest hielp in dit geval niet omdat de link tussen code en functioneel gedrag niet gezien werd.
