### ISSUE TITLE
make source code available via github

### ISSUE THREAD

**Issue by WolfgangFahl** [ABI-Team-30/Fresnel-Forms#80]
At this time i couldn't find a link to the Subversion source code repository. It would be great if the source code would be migrated here.

**Comment by AlexMekkering** [comment]
@LloydRutledge ?

**Comment by LloydRutledge** [comment]
Hi Wolfgang,

Nice to hear from you, and nice that you're interested. I'll dig up the source and put it here soon.

Regards,
Lloyd

**Comment by LloydRutledge** [comment]
Hi Wolfgang,

We have a simple copy of several SVN directories at https://github.com/ABI-Team-30/Fresnel-Forms , including in particular the subdirectory src. Is this a form you can work with?

Regards,
Lloyd

**Comment by WolfgangFahl** [comment]
Lloyd,

that looks good. Just compare https://github.com/ABI-Team-30/Fresnel-Forms/blob/master/src/main/java/nl/ou/fresnelforms/fresneltowiki/Fresnel2wiki.java with http://wiki.bitplan.com/index.php/SiDIFTemplates and you might see some similarities e.g. in http://wiki.bitplan.com/index.php/SiDIFTemplates#form and https://github.com/ABI-Team-30/Fresnel-Forms/blob/master/src/main/java/nl/ou/fresnelforms/fresneltowiki/Fresnel2wiki.java#L418

Let's see what we can make of it. Thank you very much
  Wolfgang
